### ISSUE TITLE
Using custom SSL not caddy tls 

### ISSUE THREAD

**Issue by FarzinFarzaneh** [trojanpanel/install-script#101]
Hi , how can I use my own cert.crt and private.key (custom ssl) and not the default caddy

**Comment by jonssonyan** [comment]
![image](https://user-images.githubusercontent.com/46235235/210571036-96d62033-c6df-4a01-8b42-81b1433b3a46.png)
When using the one-click installation script to build, select "Manually set the certificate path"

**Comment by FarzinFarzaneh** [comment]
Very good , just one other question can i change SSL after installation?,when the Trojan Panel is running with active users ?

**Comment by jonssonyan** [comment]
Caddy will automatically apply for and renew certificates, and there is no need to manage certificates yourself. In addition, the certificate file is in the directory /tpdata/caddy/acme/, directly overwrite the content of the certificate file and then restart the server to modify the certificate.
