### ISSUE TITLE
希望有个添加第二台服务器的详细教程

### ISSUE THREAD

**Issue by shuaibb521** [trojanpanel/install-script#104]
2个服务器  都已安装Trojan Panel Core

 第一个服务器a绑定域名A并搭建面板，第二个服务器b绑定域名B

在面板服务器里节点列表添加节点，节点内容为服务器a，域名A，则qv2ray 可以正常使用。但是服务器b域名B就无法使用。是不是得服务器b也得绑定域名A才行？？？

如果这样绑定的话qv2ray连接的时候怎么选择服务器呢？一个域名绑定2个ip？

**Comment by jonssonyan** [comment]
一个服务器对应一个域名，而且证书要对应。YouTube发布过多服务器的教程：https://www.youtube.com/watch?v=He4hcLItxSw

**Comment by shuaibb521** [comment]
补充：使用的naiveproxy
