### ISSUE TITLE
Request failed with status code 502

### ISSUE THREAD

**Issue by essoojay** [trojanpanel/install-script#107]
please how to solve this, i see it was asked a lot on here but no definite solution.

i tried on ubuntu 20.04 same error, installation succesful

tried Centos 7, same error

Cant login, it just throws this error.

Please dont just close, help please, point in the right place if this has been answered

thanks you

**Comment by sirhezar** [comment]
Hello. buy a Virtual Private Server Of digitalocean Hosting. And Setup a Ubuntu server.
You can install and Enjoy Easily.

**Comment by jonssonyan** [comment]
Use the fault detection function in the one-click installation script to view the cause of the error
