### ISSUE TITLE
脚本拉取的caddy不支持arm

### ISSUE THREAD

**Issue by juzixs** [trojanpanel/install-script#11]
docker.io/abiosoft/caddy:1.0.3
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by jonssonyan** [comment]
已支持arm64架构 https://github.com/trojanpanel/install-script/commit/7c207936b13ec1aeeef2118e784233b1eb776162
