### ISSUE TITLE
 Trojan Panel后端运行异常 （搬瓦工默认系统 ）

### ISSUE THREAD

**Issue by wenrongruan** [trojanpanel/install-script#111]
使用搬瓦工默认的系统，测试版本  centos 7 / centos 8 / Ubuntu 18.04 x86_64  
按照一键安装脚本，使用联机版本，一路默认安装下来，安装顺利，使用故障检测，全部出现以下错误
![image](https://user-images.githubusercontent.com/57340599/211292185-a2ba476f-cd96-49b8-864e-7019c12c90d6.png)

 Trojan Panel后端运行异常 日志如下：
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-01-09 18:49:25"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-01-09 18:49:26"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-01-09 18:49:26"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-01-09 18:49:27"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-01-09 18:49:28"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-01-09 18:49:30"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-01-09 18:49:33"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-01-09 18:49:40"}

**Comment by jonssonyan** [comment]
换个系统（CentOS7）或者DD系统

**Comment by CoCoThink** [comment]
同样问题，Debian 10和Cent OS 7都是这个问题

**Comment by jonssonyan** [comment]
处理器架构是什么 amd还是arm还是其他的？之前遇到过同样的报错，DD系统就好了。DD系统之后还是不好，就到TG群里@我，我私聊你。

**Comment by CoCoThink** [comment]
终于折腾好了，在节点机上安装Trojan Panel Core，数据库需要填写Trojan Panel主机的数据库而不是节点机的数据库。
