### ISSUE TITLE
搭建完成后，使用ios的shadowrocket链接使用没有问题，但是使用qv2ray在windows电脑上连接后，在日志中一直报io: read/write on close pide的错误警告

### ISSUE THREAD

**Issue by ekimmik** [trojanpanel/install-script#115]
[Warning] [64767856] v2ray.com/core/proxy/http: failed to read response from clientservices.googleapis.com > io: read/write on closed pipe

[Warning] [1632804984] v2ray.com/core/proxy/http: failed to read response from cdn.content.prod.cms.msn.com > io: read/write on closed pipe
[新建文本文档 (2).txt](https://github.com/trojanpanel/install-script/files/10387445/2.txt)

**Comment by jonssonyan** [comment]
看着像v2ray core问题，换个v2ray core版本试试。参考：https://github.com/Qv2ray/Qv2ray/issues/973

**Comment by ekimmik** [comment]
好的，谢谢。我去试下。 另外我想再问另一个问题。 我在申请证书时选择的是1自动，但是我没有在root/cert文件夹里找到证书文件，请问自动申请的话，默认存放证书路径是哪里？ 谢谢。

**Comment by ekimmik** [comment]
> 看着像v2ray core问题，换个v2ray core版本试试。参考：https://github.com/Qv2ray/Qv2ray/issues/973

我测试了4.27.5的核心，但问题还在。 我想在windows上添加信任证书再试试。请问自动下载的证书路径是什么？

**Comment by ekimmik** [comment]
> 看着像v2ray core问题，换个v2ray core版本试试。参考：https://github.com/Qv2ray/Qv2ray/issues/973

换了更低版本2.7还是不行。 我想用v2rayN客户端连接试试，请问在添加自定义配置服务器里所需的socks ip地址和端口，还有proxy代理地址和端口哪里能找到？ 因为是一键生成的，不是很清楚这些设定。 谢谢

**Comment by ekimmik** [comment]
自动下载的证书路径找到了。是在tpdata/caddy/cert里。  socks ip地址和端口，还有proxy代理地址和端口目前还没有找到

**Comment by jonssonyan** [comment]
代理地址和端口就是节点的地址和端口
socks是自己定义的监听本机和节点没关系
