### ISSUE TITLE
1.3.2版本除了vless其他方式创建的链接均无法使用

### ISSUE THREAD

**Issue by AngusChiang** [trojanpanel/install-script#116]
Mac上面使用ClashXR想要用ACL4SSR转化订阅链接使用（Vless不可转换），故想要创建Vmess或者trojan转换使用，但是创建完发现均无法使用，vless倒是正常

**Comment by jonssonyan** [comment]
试试其他设备能不能用，手机端试试

**Comment by jonssonyan** [comment]
IOS/Mac客户端支持小火箭，Windows端支持Clash.Meta。其他的客户端支持程度未知
