### ISSUE TITLE
添加节点服务器超时

### ISSUE THREAD

**Issue by qyidc** [trojanpanel/install-script#122]
面板使用是正常的，aws服务器安装core也是正常的，没有任何错误提示，在面板服务器上ping aws服务器也是通的，使用aws免费ec2添加服务器时提示超时，在面板服务器上ping aws服务器也是通的，aws服务器防火墙已经关闭。

**Comment by qyidc** [comment]
查看面板后台日志没有任何记录

**Comment by jonssonyan** [comment]
https://trojanpanel.github.io/tutorial/installation.html#%E7%9B%B8%E5%85%B3%E7%AB%AF%E5%8F%A3 查一下服务器端口有没有开放。
