### ISSUE TITLE
如何在V2RayN客户端中导入naive和hysteria

### ISSUE THREAD

**Issue by Triones009** [trojanpanel/install-script#123]
如何在V2RayN客户端中导入naive和hysteria节点？我在trojan panel中生成了naive和hysteria节点，但在v2rayn使用从剪贴板导入节点信息，没有任何反应，能说明一下在这个客户端中导入naive和hysteria节点的步骤吗？

**Comment by hajhesam** [comment]
my problem too 

right now just vless is work

**Comment by jonssonyan** [comment]
最新版加了节点详情的功能，复制的url不能用就暂时先在V2RayN手动添加节点吧，兼容性一时半会儿做不完。
