### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by AlirezaBrave** [trojanpanel/install-script#124]
hello . can anyone help me with this ? i have no idea why this is happening , don't know the reason 
appreciate if anyone could help me

curl: (22) The requested URL returned error: 403
gpg: no valid OpenPGP data found.
Failed to enable unit: Unit file docker.service does not exist.

this is happen when i put 1 to install trojan panel

**Comment by hajhesam** [comment]
explain what si your problem more ? which Linux you use ??

**Comment by AlirezaBrave** [comment]
> explain what si your problem more ? which Linux you use ??

server is raw , and also it is debian 11 . it happens on the very first command trying to install trojan panel. it gets this error and putty close immediately

**Comment by AlirezaBrave** [comment]
> explain what si your problem more ? which Linux you use ??

it is full text when i put number 1 ( for installing trojan panel at the very beginning )


请选择:1
---> 安装Docker
# Executing docker install script, commit: 1d97565eca92bb523082b7d4f530c74104e05                      d35
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-http                      s ca-certificates curl >/dev/null
+ sh -c mkdir -p /etc/apt/keyrings && chmod -R 0755 /etc/apt/keyrings
+ sh -c curl -fsSL "https://download.docker.com/linux/debian/gpg" | gpg --dearmo                      r --yes -o /etc/apt/keyrings/docker.gpg
curl: (22) The requested URL returned error: 403
gpg: no valid OpenPGP data found.
Failed to enable unit: Unit file docker.service does not exist.
---> Docker安装失败

**Comment by U-nanimou-S** [comment]
use ubuntu 22  and try again
