### ISSUE TITLE
服务器一旦重启就连不上数据库

### ISSUE THREAD

**Issue by BrunuhVille** [trojanpanel/install-script#125]
{"level":"error","msg":"数据库连接异常 err: dial tcp 127.0.0.1:9507: connect: connection refused","time":"2023-01-15 12:28:08"}

搭建好就不能重启，重启一次就坏掉了，debian和ubuntu都是这样

**Comment by jonssonyan** [comment]
这个看样子不是tp的问题。尝试换个系统试试呢

**Comment by kuangjun2021** [comment]
这个问题有解决吗？自从更新到新版本后，原来正常的服务器也变成这样了。

**Comment by dengkl1007** [comment]
我用centos7也一样。系统reboot后日志里会报数据库连接异常，进去docker把tp的几个容器restart后，这次就不报 了，下次系统重启还需要进docker里操作

**Comment by jonssonyan** [comment]
Docker和里面的容器都是自动启动的，重启服务器就可以了。

> 我用centos7也一样。系统reboot后日志里会报数据库连接异常，进去docker把tp的几个容器restart后，这次就不报 了，下次系统重启还需要进docker里操作
