### ISSUE TITLE
[BUG] 安装过程中对于Caddy容器的启动成功检测可能有问题

### ISSUE THREAD

**Issue by juilletVent** [trojanpanel/install-script#126]
## Caddy容器运行检测的关键判断位置

https://github.com/trojanpanel/install-script/blob/b7971c3d7db3ee328f10f474c4ae30af2895aab6/install_script_standalone.sh#L576

将该命令拷出直接执行：

~~~shell
# 无任何输出
docker ps -q -f "name=^trojan-panel-caddy$" -f "status=running"
~~~

发现无任何输出，因此，脚本判定容器启动失败，终止安装过程。但是，Caddy其实启动成功了，使用docker ps查看，发现容器已经启动，访问80端口能够正确重定向到8863，并返回静态站点。修改命令后再次执行：

~~~shell
# 删除了正则的头尾限定符：^ $
docker ps -q -f "name=trojan-panel-caddy" -f "status=running"
~~~

正确输出正在运行的docker容器ID，可能是BUG吧，要不你看看？？

## 环境信息

系统：
CentOS Linux release 7.9.2009 (Core)
Linux quick-choice-3.localdomain 6.1.5-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 11 12:53:42 EST 2023 x86_64 x86_64 x86_64 GNU/Linux
Docker版本：Docker version 1.13.1, build 7d71120/1.13.1

**Comment by juilletVent** [comment]
## 测试情况

~~~
[root@quick-choice-3 ~]# docker ps -q -f "name=trojan-panel-caddy"
899cbca8435b
[root@quick-choice-3 ~]# docker ps -q -f "name=trojan-panel-caddy" -f "status=running"
899cbca8435b
[root@quick-choice-3 ~]# docker ps -q -f "name=^trojan-panel-caddy$" -f "status=running"
[root@quick-choice-3 ~]# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                     NAMES
899cbca8435b        caddy:2.6.2         "caddy run --confi..."   8 minutes ago       Up 8 minutes                                  trojan-panel-caddy
7d0ff883bc1e        mariadb:10.2        "docker-entrypoint..."   3 days ago          Up 7 hours          0.0.0.0:17578->3306/tcp   trojan-mariadb
[root@quick-choice-3 ~]# docker -v
Docker version 1.13.1, build 7d71120/1.13.1

~~~

**Comment by jonssonyan** [comment]
感谢你的详细反馈，不过好像不是Bug，我测试了都可以输出，可能是Docker版本不一样，低版本不支持正则表达式。
![image](https://user-images.githubusercontent.com/46235235/215510310-1e6358d5-5fb0-47ae-bdb2-5aca80f294b3.png)

**Comment by juilletVent** [comment]
确实是版本问题，更新Docker版本后成功安装，非常感觉您的无私奉献。我是一名前端开发人员，有需要技术支持的话，可以艾特我

**Comment by jonssonyan** [comment]
👍👍
