### ISSUE TITLE
single session user

### ISSUE THREAD

**Issue by fgsadmin** [trojanpanel/install-script#127]
Hi everyone
In troajan panel can`t add single session user , i need it
How to add single session user?
Thanks

**Comment by yaramahmadi** [comment]
Hi everyone
How can I see which version is currently installed and also update to the new version? (without losing User Data)

**Comment by darya1012** [comment]
> سلام به همه
> در پنل troajan نمی توان کاربر تک جلسه ای اضافه کرد، من به آن نیاز دارم
> چگونه کاربر تک جلسه را اضافه کنیم؟
> با تشکر

Hello
This is a good and practical suggestion, please take care of it.
