### ISSUE TITLE
Update to Last Version

### ISSUE THREAD

**Issue by yaramahmadi** [trojanpanel/install-script#128]
Hi everyone
How can I see which version is currently installed and also update to the new version? (without losing User Data)

**Comment by ramtin140** [comment]
Its my same problem too, would you please support

**Comment by mhmkt** [comment]
If you run the installation script you can see the version at the top and for updating you can use options number 6 and 7 for panel and core respectively.

**Comment by jonssonyan** [comment]
The latest one-click installation script already supports the option of online update and viewing system version
