### ISSUE TITLE
添加服务器超时

### ISSUE THREAD

**Issue by lanxuewsr** [trojanpanel/install-script#132]
大佬您好！
请问，我在vps上安装了Trojan Panel和Core，但在面板上的“服务器列表”里添加服务器，IP填的127.0.0.1，但状态显示“超时”。还试了另外一台vps，面板和Core都安装了，填这台服务器的IP，也显示“超时”。
是不是我添加的方式不对？
非常感谢！

**Comment by amirsaeedinejad** [comment]
add your public ip server

**Comment by lanxuewsr** [comment]
非常感谢大佬！是我之前操作错误了，脚本本身完全没问题，给大佬添麻烦了。（手动捂脸）o(>﹏<)o

**Comment by h0we** [comment]
> 非常感谢大佬！是我之前操作错误了，脚本本身完全没问题，给大佬添麻烦了。（手动捂脸）o(>﹏<)o

大佬 我遇到了同样的问题 内网IP 与公网IP都不成功。请问下大佬是怎么解决的。

**Comment by h0we** [comment]
> > > 非常感谢大佬！是我之前操作错误了，脚本本身完全没问题，给大佬添麻烦了。（手动捂脸）o(>﹏<)o
> > 
> > 
> > 大佬 我遇到了同样的问题 内网IP 与公网IP都不成功。请问下大佬是怎么解决的。
> 
> 我是以为装了Core，实际上并没有，再用脚本装上Core就好了o(>﹏<)o

都装了 依然离线  o(>﹏<)o
