### ISSUE TITLE
data traffic counter not wotking

### ISSUE THREAD

**Issue by aliruss** [trojanpanel/install-script#135]
this is some bugs on the lastest vertion 

+ proxy dns not working with caddy 
+ data counter not working

**Comment by farnoxd** [comment]
新版本不支持流量统计，请尽快修复

**Comment by rezash061** [comment]
the same here!✋🏻

**Comment by mazarjan** [comment]
Same problem

**Comment by IRANWEBFA** [comment]
please fix it

**Comment by 3ehzaad** [comment]
It is fixed, update to 1.21

**Comment by mazarjan** [comment]
> The latest version v2.0.1 has been repaired, directly run the one-click installation script, and then enter 6 and 7, automatic update, barrier-free data migration, and no data loss.

Unfortunately, not solved for me
