### ISSUE TITLE
新版面板中服务器列表添加问题

### ISSUE THREAD

**Issue by mulder125** [trojanpanel/install-script#139]
新版面板可以添加多服务器，但有个问题是添加服务器时只能填写IP。
填写域名添加不上，未来是否会支持域名？（因为服务器IP不定时会变动）

**Comment by jonssonyan** [comment]
你是nat机器么？可以支持域名，后续会更新。

**Comment by mulder125** [comment]
好的，谢谢～
不是NAT机，只是有服务器使用家宽网，用PPPoE取得动态IP的，故需要用域名

**Comment by jonssonyan** [comment]
v2.0.3所有端口已经可以用户自定义了。

**Comment by jonssonyan** [comment]
域名的校验已经去除了。
