### ISSUE TITLE
登陆报错502

### ISSUE THREAD

**Issue by dongxicc** [trojanpanel/install-script#143]
查看ui 日志api接口报错,nginx里配置的
location /api {
        proxy_pass http://127.0.0.1:8081;
    }

这个8081是什么服务,文档里也没看到说明

**Comment by dongxicc** [comment]
本地端口也没看到监听8081的服务

**Comment by jonssonyan** [comment]
8081是后端监听的端口。运行脚本里面的故障检测，日志贴出来
