### ISSUE TITLE
添加服务器时填入ip后显示超时

### ISSUE THREAD

**Issue by maomaochong1574** [trojanpanel/install-script#146]
填入自己的ip地址后显示超时

**Comment by wossig** [comment]
encounter the same issue, does anybody knows how to fix?

**Comment by wossig** [comment]
Resolved, It need both Trojan Panel and Trojan core to be installed

**Comment by maomaochong1574** [comment]
thanks

**Comment by jonssonyan** [comment]
节点服务器需要安装trojan-panel-core，并且开放对应的通信端口（默认8100），文档里都有说明，仔细看看。
