### ISSUE TITLE
添加节点报错

### ISSUE THREAD

**Issue by deartonyz** [trojanpanel/install-script#149]
web端添加节点报错
open bin/xray/config/config-30443-{"network":"tcp","security":"tls","tlsSettings":{},"xtlsSettings":{},"wsSettings":{"path":"/trojan-panel-websocket-path"}}.json: no such file or directory

日志如下:
{"level":"error","msg":"创建xray bin/xray/config/config-32333-{\"network\":\"tcp\",\"security\":\"tls\",\"tlsSettings\":{},\"xtlsSettings\":{},\"wsSettings\":{\"path\":\"/trojan-panel-websocket-path\"}}.json文件异常 err: open bin/xray/config/config-32333-{\"network\":\"tcp\",\"security\":\"tls\",\"tlsSettings\":{},\"xtlsSettings\":{},\"wsSettings\":{\"path\":\"/trojan-panel-websocket-path\"}}.json: no such file or directory","time":"2023-02-22 04:49:06"}
{"level":"error","msg":"创建xray bin/xray/config/config-32333-{\"network\":\"tcp\",\"security\":\"tls\",\"tlsSettings\":{},\"xtlsSettings\":{},\"wsSettings\":{\"path\":\"/trojan-panel-websocket-path\"}}.json文件异常 err: open bin/xray/config/config-32333-{\"network\":\"tcp\",\"security\":\"tls\",\"tlsSettings\":{},\"xtlsSettings\":{},\"wsSettings\":{\"path\":\"/trojan-panel-websocket-path\"}}.json: no such file or directory","time":"2023-02-22 04:49:06"}
{"level":"error","msg":"创建xray bin/xray/config/config-32333-{\"network\":\"tcp\",\"security\":\"tls\",\"tlsSettings\":{},\"xtlsSettings\":{},\"wsSettings\":{\"path\":\"/trojan-panel-websocket-path\"}}.json文件异常 err: open bin/xray/config/config-32333-{\"network\":\"tcp\",\"security\":\"tls\",\"tlsSettings\":{},\"xtlsSettings\":{},\"wsSettings\":{\"path\":\"/trojan-panel-websocket-path\"}}.json: no such file or directory","time":"2023-02-22 04:49:07"}
{"level":"error","msg":"创建xray bin/xray/config/config-32333-{\"network\":\"tcp\",\"security\":\"tls\",\"tlsSettings\":{},\"xtlsSettings\":{},\"wsSettings\":{\"path\":\"/trojan-panel-websocket-path\"}}.json文件异常 err: open bin/xray/config/config-32333-{\"network\":\"tcp\",\"security\":\"tls\",\"tlsSettings\":{},\"xtlsSettings\":{},\"wsSettings\":{\"path\":\"/trojan-panel-websocket-path\"}}.json: no such file or directory","time":"2023-02-22 04:49:07"}
{"level":"error","msg":"创建xray bin/xray/config/config-32333-{\"network\":\"tcp\",\"security\":\"tls\",\"tlsSettings\":{},\"xtlsSettings\":{},\"wsSettings\":{\"path\":\"/trojan-panel-websocket-path\"}}.json文件异常 err: open bin/xray/config/config-32333-{\"network\":\"tcp\",\"security\":\"tls\",\"tlsSettings\":{},\"xtlsSettings\":{},\"wsSettings\":{\"path\":\"/trojan-panel-websocket-path\"}}.json: no such file or directory","time":"2023-02-22 04:49:08"}
{"level":"error","msg":"process has been stoped. apiPort: 32333","time":"2023-02-22 04:49:10"}
{"level":"error","msg":"process has been stoped. apiPort: 32333","time":"2023-02-22 04:49:12"}
{"level":"error","msg":"process has been stoped. apiPort: 32333","time":"2023-02-22 04:49:13"}
{"level":"error","msg":"process has been stoped. apiPort: 32333","time":"2023-02-22 04:49:13"}
{"level":"error","msg":"process has been stoped. apiPort: 32333","time":"2023-02-22 04:49:13"}
{"level":"error","msg":"process has been stoped. apiPort: 32333","time":"2023-02-22 04:49:13"}
{"level":"error","msg":"process has been stoped. apiPort: 32333","time":"2023-02-22 04:49:13"}
{"level":"error","msg":"process has been stoped. apiPort: 32333","time":"2023-02-22 04:49:13"}
{"level":"error","msg":"process has been stoped. apiPort: 32333","time":"2023-02-22 04:49:14"}
{"level":"error","msg":"process has been stoped. apiPort: 32333","time":"2023-02-22 04:49:14"}
{"level":"error","msg":"process has been stoped. apiPort: 32333","time":"2023-02-22 04:49:14"}
{"level":"error","msg":"process has been stoped. apiPort: 32333","time":"2023-02-22 04:49:14"}
{"level":"error","msg":"process has been stoped. apiPort: 32333","time":"2023-02-22 04:49:15"}
{"level":"error","msg":"process has been stoped. apiPort: 32333","time":"2023-02-22 04:49:15"}
{"level":"error","msg":"process has been stoped. apiPort: 32333","time":"2023-02-22 04:49:16"}

**Comment by jonssonyan** [comment]
trojan-panel-ui  trojan-panel trojan-panel-core的版本是多少？用最新版试试？

**Comment by deartonyz** [comment]
更新了新版本，问题已解决！谢谢
