### ISSUE TITLE
debian11 kenel5.10

### ISSUE THREAD

**Issue by ZYLLLLLL** [trojanpanel/install-script#15]
搭建完后caddy端口访问正常，面板无法进入

**Comment by jonssonyan** [comment]
重启服务器看看问题还存不存在。
如果不行，就运行脚本里面故障检测的选项，看哪里有问题，然后把有问题的应用卸载重装（脚本里面有对应应用的卸载选项）。
如果以上还不能解决问题，DD系统再使用脚本重装。
