### ISSUE TITLE
大佬。面板好像从2.x版本退回1.0版本了？

### ISSUE THREAD

**Issue by BrunuhVille** [trojanpanel/install-script#150]
是发生情况了吗

**Comment by jonssonyan** [comment]
没有啊，你遇到了什么奇怪的事情？

**Comment by BrunuhVille** [comment]
> 没有啊，你遇到了什么奇怪的事情？

我是看release目前只有v1.0的版本了

**Comment by jonssonyan** [comment]
release我删的，更新记录见：https://trojanpanel.github.io/change/change-log.html

**Comment by jonssonyan** [comment]
迁移了，维护两份记录比较麻烦，详细的更新记录见[TG频道](https://t.me/trojanpanel)
