### ISSUE TITLE
用联机版安装脚本，显示的菜单是乱码（centos 7\8),系统显示汉字正常（用date命令可正常显示汉字），不知什么情况？

### ISSUE THREAD

**Issue by cooge70** [trojanpanel/install-script#154]

**Comment by cooge70** [comment]
我用的是finalshell来远程VPS

**Comment by cooge70** [comment]
1. 瀹夎Trojan Panel
2. 瀹夎Trojan Panel Core
3. 瀹夎Caddy TLS
4. 瀹夎MariaDB
5. 瀹夎Redis

**Comment by cooge70** [comment]
2023年 02月 28日 星期二 03:09:56 UTC

**Comment by cooge70** [comment]
后来重装OS为Ubuntu 22.10 x64，瞎折腾了下，竟然可以正常显示了。估计跟系统zh_CN.UTF-8有关。

**Comment by jonssonyan** [comment]
是的，自己服务器的原因。
