### ISSUE TITLE
为啥Docker没启动？

### ISSUE THREAD

**Issue by pcitme** [trojanpanel/install-script#157]
---> 你已经安装了Docker
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
.
.
.
.
.
.
请选择申请证书的方式(1/acme 2/zerossl 默认:1/acme): 1
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
---> Caddy安装失败或运行异常,请尝试修复或卸载重装

**Comment by pcitme** [comment]
我擦  内存要求1G  我可怜的小鸡只有384.。。

**Comment by jonssonyan** [comment]
正常内存占用在300M-400M，512M都捉襟见肘，你这明显不够用。
