### ISSUE TITLE
能不能添加一个导出到clash订阅的功能？

### ISSUE THREAD

**Issue by Shuazijun** [trojanpanel/install-script#16]
rt，参考Jrohy/trojan的面板，做个导出订阅的功能，并且支持修改导出模板的功能（方便引入规则组这些参数），还有就是能不能在网页上显示当前trojango运行访问状态的信息？（比如继承性xterm仿真终端）

**Comment by jonssonyan** [comment]
订阅功能可以的，但是时间有限慢慢来吧。仿真终端这这个对于本地节点还好，对于远程节点似乎不太通用，有点鸡肋。

**Comment by jonssonyan** [comment]
> rt，参考Jrohy/trojan的面板，做个导出订阅的功能，并且支持修改导出模板的功能（方便引入规则组这些参数），还有就是能不能在网页上显示当前trojango运行访问状态的信息？（比如继承性xterm仿真终端）

我的网站：https://jonssonyan.com

**Comment by jonssonyan** [comment]
可以，安排。

**Comment by jonssonyan** [comment]
v1.2.0开发好了。https://github.com/trojanpanel/install-script/commit/e6103fc4e22dd7e974529c4b387cf91948301053
