### ISSUE TITLE
Redis初始化失败

### ISSUE THREAD

**Issue by pm0725** [trojanpanel/install-script#160]
日志如下:
{"level":"error","msg":"Redis初始化失败 err: dial tcp 127.0.0.1:0: connect: connection refused","time":"2023-03-03 18:24:22"}
{"level":"error","msg":"Redis初始化失败 err: dial tcp 127.0.0.1:0: connect: connection refused","time":"2023-03-03 18:24:26"}
{"level":"error","msg":"dial tcp 127.0.0.1:9507: connect: connection refused","time":"2023-03-03 18:25:44"}
{"level":"error","msg":"Error 1146 (42S02): Table 'trojan_panel_db.account' doesn't exist","time":"2023-03-03 18:26:43"}
{"level":"error","msg":"Error 1146 (42S02): Table 'trojan_panel_db.account' doesn't exist","time":"2023-03-03 18:27:43"}
{"level":"error","msg":"Error 1146 (42S02): Table 'trojan_panel_db.account' doesn't exist","time":"2023-03-03 18:28:43"}
{"level":"error","msg":"Error 1146 (42S02): Table 'trojan_panel_db.account' doesn't exist","time":"2023-03-03 18:29:44"}
{"level":"error","msg":"Error 1146 (42S02): Table 'trojan_panel_db.account' doesn't exist","time":"2023-03-03 18:30:43"}
{"level":"error","msg":"Error 1146 (42S02): Table 'trojan_panel_db.account' doesn't exist","time":"2023-03-03 18:31:43"}
{"level":"error","msg":"Error 1146 (42S02): Table 'trojan_panel_db.account' doesn't exist","time":"2023-03-03 18:32:43"}
{"level":"error","msg":"Error 1146 (42S02): Table 'trojan_panel_db.account' doesn't exist","time":"2023-03-03 18:33:43"}
{"level":"error","msg":"Error 1146 (42S02): Table 'trojan_panel_db.account' doesn't exist","time":"2023-03-03 18:34:43"}
{"level":"error","msg":"Error 1146 (42S02): Table 'trojan_panel_db.account' doesn't exist","time":"2023-03-03 18:35:43"}
{"level":"error","msg":"Error 1146 (42S02): Table 'trojan_panel_db.account' doesn't exist","time":"2023-03-03 18:36:43"}

**Comment by jonssonyan** [comment]
1. Redis端口设置成0了
2. 数据库密码设置太简单，库被删了
