### ISSUE TITLE
Issue规范/Issue specification

### ISSUE THREAD

**Issue by jonssonyan** [trojanpanel/install-script#163]
如果遇到问题，请提供以下信息，否则统一关闭。

1. 问题描述或者复现步骤
2. 操作系统信息
3. Trojan Panel相关应用版本
4. 错误日志

If you encounter any problems, please provide the following information, otherwise it will be closed.

1. Problem description or steps to reproduce
2. operating system information
4. Trojan Panel related application version
5. error log

**Comment by kkksa528** [comment]
你是脾气好有耐心，大部分人要么不理会issues，要么直接关闭

**Comment by Mahanfix** [comment]
من چندین بار با سرورهای مختلف تست کردم هر بار که نصب کردم همه چیزش دررست نصب شود موقع وارد کردن یوزر و پسورد ارور تایم اوت میزنه
