### ISSUE TITLE
xray启动报错

### ISSUE THREAD

**Issue by kkksa528** [trojanpanel/install-script#165]
{"level":"error","msg":"xray 进程等待错误 err: signal: killed","time":"2023-03-09 12:29:02"}
{"level":"error","msg":"xray process state fail err: \u003cnil\u003e","time":"2023-03-09 12:29:02"}
{"level":"error","msg":"xray 进程等待错误 err: signal: killed","time":"2023-03-09 12:31:51"}
{"level":"error","msg":"xray process state fail err: \u003cnil\u003e","time":"2023-03-09 12:31:51"}
{"level":"error","msg":"xray 进程等待错误 err: signal: killed","time":"2023-03-09 12:36:51"}
{"level":"error","msg":"xray process state fail err: \u003cnil\u003e","time":"2023-03-09 12:36:51"}
{"level":"error","msg":"xray 进程等待错误 err: signal: killed","time":"2023-03-09 12:37:51"}
{"level":"error","msg":"xray process state fail err: \u003cnil\u003e","time":"2023-03-09 12:37:51"}
{"level":"error","msg":"xray 进程等待错误 err: signal: killed","time":"2023-03-09 12:38:51"}
{"level":"error","msg":"xray process state fail err: \u003cnil\u003e","time":"2023-03-09 12:38:51"}
{"level":"error","msg":"xray 进程等待错误 err: signal: killed","time":"2023-03-09 12:38:53"}
{"level":"error","msg":"xray process state fail err: \u003cnil\u003e","time":"2023-03-09 12:38:53"}
{“level”：“error”，“msg”：“xray 添加用户错误：rpc 错误：code = DeadlineExceeded desc = context deadline exceeded”，“time”：“2023-03-09 12:42:33”}
{"level":"error","msg":"Xray 调试 api 添加用户错误 err: gRPC 连接异常","time":"2023-03-09 12:42:33"}

拙见：安装结束后尝试启动xray，这样安装后立马查看日志就立刻能意识哪些模块安装错误，或者直接加上xray等内核监控（嘿嘿）

**Comment by kkksa528** [comment]
这不是bug，小问题，重装core半分钟解决

**Comment by jonssonyan** [comment]
应该是网络不稳定的问题，出问题可以重启、重建节点、重装对于的应用都是基本操作，脚本里面有卸载相应应用的选项。
