### ISSUE TITLE
请求添加自定义分享链接的功能

### ISSUE THREAD

**Issue by KyoMio** [trojanpanel/install-script#166]
面板导出的分享链接无法被客户端软件识别，缺少参数

建议添加自定义分享链接的功能，可以自定义多种格式的分享链接，如小火箭、v2rayN等等。

（面板的工程文件为啥不开源啊zzzz，还加密了:see_no_evil:）

**Comment by jonssonyan** [comment]
目前对于识别不了的客户端就先添加单个节点，也可以手动添加，节点里面添加了详情的按钮。
准备是根据Headers User-Agent 服务端返回不同的格式，而不是分别开发多个分享链接，有这个计划，但是到时候我觉得微调会比较多。
部署脚本是公开的，面板没开源，文档常见问题里面写了，直播也说过这个事情。主要原因是能够应对开发的需求，开源以后也会有很多其他的问题出现，总之没必要，不过可以肯定的是无后门也不会收费。

**Comment by KyoMio** [comment]
> 目前对于识别不了的客户端就先添加单个节点，也可以手动添加，节点里面添加了详情的按钮。 准备是根据Headers User-Agent 服务端返回不同的格式，而不是分别开发多个分享链接，有这个计划，但是到时候我觉得微调会比较多。 部署脚本是公开的，面板没开源，文档常见问题里面写了，直播也说过这个事情。主要原因是能够应对开发的需求，开源以后也会有很多其他的问题出现，总之没必要，不过可以肯定的是无后门也不会收费。

谢谢回复，手动在客户端添加节点肯定是没问题的，但是用了面板不就是想更方便点嘛，能适配客户端的话体验会更好些。比如现在的vmess节点，用小火箭扫码添加的话ws的伪装host不会自动填入。诸如此类。

**Comment by jonssonyan** [comment]
订阅和复制URL这块还只是开发了初版，后来就没改过，精力放在其他功能的开发上面了，以后慢慢完善吧，先给标上label。

**Comment by Duke-li** [comment]
> 订阅和复制URL这块还只是开发了初版，后来就没改过，精力放在其他功能的开发上面了，以后慢慢完善吧，先给标上label。

我测试了一下，主要是复制URL无法识别，在v2rayN中无法识别的url类型包括（Xray下的Vmess节点和Trojan-go节点），一般url是Vmess://+base64编码后的字符串。
例如vmess节点信息是这个
`{
  "v": "2",
  "ps": "test-cdn",
  "add": "domain.com",
  "port": "2053",
  "id": "ididid",
  "aid": "0",
  "scy": "auto",
  "net": "ws",
  "type": "none",
  "host": "",
  "path": "/trojan-panel-websocket-path",
  "tls": "tls",
  "sni": "",
  "alpn": ""
}`

加密后的信息通用的节点识别方式是这个结果
`vmess://ewogICJ2IjogIjIiLAogICJwcyI6ICJ0ZXN0LWNkbiIsCiAgImFkZCI6ICJkb21haW4uY29tIiwKICAicG9ydCI6ICIyMDUzIiwKICAiaWQiOiAiaWRpZGlkIiwKICAiYWlkIjogIjAiLAogICJzY3kiOiAiYXV0byIsCiAgIm5ldCI6ICJ3cyIsCiAgInR5cGUiOiAibm9uZSIsCiAgImhvc3QiOiAiIiwKICAicGF0aCI6ICIvdHJvamFuLXBhbmVsLXdlYnNvY2tldC1wYXRoIiwKICAidGxzIjogInRscyIsCiAgInNuaSI6ICIiLAogICJhbHBuIjogIiIKfQ==`

**Comment by jonssonyan** [comment]
xray的vmess是vmess aead，v2rayN不支持vmess aead的分享链接，所以页识别不了
https://github.com/XTLS/Xray-core/issues/91
