### ISSUE TITLE
有一定几率触发Caddy安装失败

### ISSUE THREAD

**Issue by Android-AwesomeRoy** [trojanpanel/install-script#168]
<img width="874" alt="image" src="https://user-images.githubusercontent.com/19187129/224253818-976c0ec8-3dc8-473e-bdc9-fd29d6499ace.png">

在sudo环境下安装，出现问题后直接连sudo都退掉了。

**Comment by liyehuicn** [comment]
应该是80端口被占用了

**Comment by jonssonyan** [comment]
从你的截图上看不出来什么原因，我之前caddy安装失败是系统环境的问题，惯例我建议DD系统。
