### ISSUE TITLE
重启后连接不上数据库，再重装后打不开前端

### ISSUE THREAD

**Issue by ZXSIPROMISE** [trojanpanel/install-script#169]
1. 问题描述或者复现步骤
2. 操作系统信息
3. Trojan Panel相关应用版本
4. 错误日志

 [![ppM375t.png](https://s1.ax1x.com/2023/03/12/ppM375t.png)](https://imgse.com/i/ppM375t)

1. 第一次安装顺利，vps重启后前端显示network error，日志显示连接不上数据库。
2. ubuntu 20.04 oracle arm
3. Trojan Panel v2.0.4  trojan-panel-core v2.0.3
4. 重装后打不开前端 没有日志文件

**Comment by jonssonyan** [comment]
故障检测看看，把日志文件贴出来。关键的IP和域名进行隐藏。

**Comment by ZXSIPROMISE** [comment]
故障检查显示正常，没有日志文件。
![Picsee-20230312200730.png](http://129.146.74.103:7791/i/2023/03/13/640e93a35b6f7.png)
![Picsee-20230312195726.png](http://129.146.74.103:7791/i/2023/03/13/640e93a3e31a5.png)
![Picsee-20230312200127.png](http://129.146.74.103:7791/i/2023/03/13/640e93a479305.png)
![Picsee-20230312200008.png](http://129.146.74.103:7791/i/2023/03/13/640e93a595046.png)
![Picsee-20230312195930.png](http://129.146.74.103:7791/i/2023/03/13/640e93a6a3699.png)

**Comment by jonssonyan** [comment]
关闭防火墙，如果有面板，面板上面也要开放对应端口。

**Comment by ZXSIPROMISE** [comment]
都设置了，首次安装一切都正常，也可以正常使用。vps重启后就变成上述问题

**Comment by jonssonyan** [comment]
我感觉还是端口的问题。一键安装脚本有个改前端端口的设置，换个端口试试。
