### ISSUE TITLE
Centos7运行起来FQ失败

### ISSUE THREAD

**Issue by Lancger** [trojanpanel/install-script#17]
[ERROR] 2022/09/16 08:17:40 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | freedom failed to dial v1.mux.cool:9527 | dial tcp: lookup v1.mux.cool on 127.0.0.11:53: no such host
[INFO]  2022/09/16 08:17:40 user b4fc1369dd766eca295fb495b0938843becbac59fc5cb273b320aaa5 from 118.143.233.72:4325 tunneling to v1.mux.cool:9527 closed sent: 0 B recv: 0 B

![image](https://user-images.githubusercontent.com/16274422/190591682-5070a23b-b019-4c76-9100-77b71cc2351b.png)

**Comment by jonssonyan** [comment]
看报错，初步判断原因是服务器ping这个域名不通，v1.mux.cool 是你的域名么？你在那个地方输入的这个域名？

**Comment by Lancger** [comment]
v1.mux.cool   这个域名不是我这边的，我试过阿里云的轻量机器，初次跑，也有这个报错

**Comment by jonssonyan** [comment]
查了一下，这个域名是内置的，DD系统试试，这样系统纯净一点.
