### ISSUE TITLE
vless+tcp+xtls-rprx-direct not working on port 443

### ISSUE THREAD

**Issue by hosseinjalaei** [trojanpanel/install-script#170]
Hello. "vless + tcp + xtls-rprx-direct" config not working on port 443, but when I change the port it works. Please help.

**Comment by jonssonyan** [comment]
It seems that it is not a problem with the panel. There is a problem with your 443 port. Check whether a 443 port is blocked or occupied by other programs.

**Comment by hosseinjalaei** [comment]
No Sir, there is no problem when I use vless+tcp+tls on port 443, it works fine, but when I change it to xtls-rprx-direct, it doesn't work anymore. Thanks for answering.
