### ISSUE TITLE
add server porblem

### ISSUE THREAD

**Issue by MHP370** [trojanpanel/install-script#171]
Hi guys

How I can add new server ?
what's server port api ?
thanks

**Comment by jonssonyan** [comment]
The default 8100 is fine if there is no special requirement

**Comment by Merdan-Kurbanov** [comment]
i type to server ip my vps ip and port is staying 8100 but after adding status stays timedout and getting error on adding nodes

**Comment by Merdan-Kurbanov** [comment]
Solved !
installed trojan panel and set different server ip port  after that it starts work

**Comment by Mrered** [comment]
I had tried to add my second server into the first server's panel, but I don't know why the container in the second server restart continuously forever with no logs. I need some guild too!
大佬，我IP（已确认放行）、端口、密码啥的都检查好几遍了，还是连不上第二个的服务器上的core！求指点！ @jonssonyan

**Comment by amink69** [comment]
i got error when add new server with this defult port.

**Comment by jonssonyan** [comment]
Check if the system is running normally
查看系统是否运行正常
