### ISSUE TITLE
数据库用户表pass生成规则是什么？

### ISSUE THREAD

**Issue by asenshi** [trojanpanel/install-script#172]
有需求需要直接对数据库进行批量添加删除用户。
想请问一下，trojan panel 是如何储存用户名和密码生成用户 pass 的？

**Comment by jonssonyan** [comment]
密码加密是加盐的。直接调接口吧，浏览器开F12，所有接口都能看到。调登录接口拿到token，然后请求其他接口加一个携带token请求头就可以了。
