### ISSUE TITLE
Add server timed out error

### ISSUE THREAD

**Issue by Merdan-Kurbanov** [trojanpanel/install-script#175]
hello i tried to add server and ip is my vps ip port stays default 8100 but it doesnt works and status is timed out

**Comment by IGuanggg** [comment]
me too

**Comment by Merdan-Kurbanov** [comment]
Solved !
installed trojan panel and set different server ip port after that it starts work

**Comment by Mrered** [comment]
#225 I had tried to add my second server into the first server's panel, but I don't know why the container in the second server restart continuously forever with no logs. I need some guild too!
