### ISSUE TITLE
与节点服务器的grpc通信在一段时间后报错

### ISSUE THREAD

**Issue by SchoenJoanne** [trojanpanel/install-script#179]
运行系统：core 和 panel 分别运行在两台 Debian 11 上
版本：v2.04

节点服务器在运行一段时间后显示超时。
查看 core 日志 报错：
{"level":"error","msg":"xray add user err: rpc error: code = DeadlineExceeded desc = context deadline exceeded","time":"2023-03-22 22:47:03"}
{"level":"error","msg":"Xray调用api添加用户错误 err: gRPC连接异常","time":"2023-03-22 22:47:03"}

查看panel 日志报错：
{"level":"error","msg":"gRPC ping 异常 ip: ******** grpc port: 8100 err: rpc error: code = DeadlineExceeded desc = context deadline exceeded","time":"2023-03-22 22:48:48"}

重启core docker容器后恢复正常。
大概8分钟后开始重新报错。
报错不影响节点正常使用。可能会影响流量统计和节点服务器新用户的获取？

主面板本机的 core 没有出现这个问题。

**Comment by jonssonyan** [comment]
本机通信效率比较高，如果是远程节点通信收到网络波动的影响。
偶尔显示一次没关系，如果长时间有错误日志就把节点删了重新添加 一个试试。

**Comment by SchoenJoanne** [comment]
> 本机通信效率比较高，如果是远程节点通信收到网络波动的影响。 偶尔显示一次没关系，如果长时间有错误日志就把节点删了重新添加 一个试试。



DD系统重装了，还是一样超时。2个节点服务器都是这样的问题。
另外，超时一段时间过后，服务器会直接宕机无法连接。需要进vps面板硬重启。
应该不是网络连接的问题。。会不会是句柄数不够？

**Comment by SchoenJoanne** [comment]
目前添加5个节点服务器，除了面板本机以外，2个正常工作，2个grpc始终会在若干小时后断开通信。全部节点服务器都是DD系统后纯净安装。我再试试不用Debain 会不会出现这样的问题

**Comment by xt1085** [comment]
> 目前添加5个节点服务器，除了面板本机以外，2个正常工作，2个grpc始终会在若干小时后断开通信。全部节点服务器都是DD系统后纯净安装。我再试试不用Debain 会不会出现这样的问题

我也发现有这种情况，你是怎么解决的

**Comment by jonssonyan** [comment]
> 目前添加5个节点服务器，除了面板本机以外，2个正常工作，2个grpc始终会在若干小时后断开通信。全部节点服务器都是DD系统后纯净安装。我再试试不用Debain 会不会出现这样的问题

可能是网络的问题

**Comment by xt1085** [comment]
刚刚试过了全换成ubuntu系统还是出现这种问题，

**Comment by jonssonyan** [comment]
试试最新版，最新版对系统性能进行了优化。
