### ISSUE TITLE
按照脚本安装完成后登陆管理面板提示错误

### ISSUE THREAD

**Issue by xingccn** [trojanpanel/install-script#18]
按照脚本安装完成后登陆管理面板提示错误
Request failed with status code 502
这是什么原因呢？

**Comment by jonssonyan** [comment]
重启之后看看问题有没有解决。如果不行则使用以下排查方法。
首先运行一下脚本里面的修复功能看是那个容器报错了，然后使用命令：docker logs [容器ID]，查看容器内的错误日志，最后对症下药。
