### ISSUE TITLE
图标没了，怎么改

### ISSUE THREAD

**Issue by xiaopan369** [trojanpanel/install-script#181]
### 
图标没了，怎么改
![trojan panel](https://user-images.githubusercontent.com/96175047/227009812-2d8f43b9-fd46-4893-a9b6-2922a150bbb4.png)

**Comment by jonssonyan** [comment]
当时为了方便直接用的图床，图床链接失效了。下个版本自定义Logo的功能已经开发了，等下次发版就可以用了。

**Comment by xiaopan369** [comment]
> 当时为了方便直接用的图床，图床链接失效了。下个版本自定义Logo的功能已经开发了，等下次发版就可以用了。

哦哦好的，我有一个问题如果我搭建的主面板挂了我可以把其他绑定在这个面板上的节点数据库什么的改成新的面板上吗，然后订阅有时候订阅不上应该是延迟问题我在国内找台服务器部署面板会被封吗

**Comment by xiaopan369** [comment]
> 面板挂了没关系，重新搭建面板就行，只要数据库没挂就行，代表数据是安全的。重新搭建面板填数据库相关的信息的时候填之前搭建的数据库就行了。 不建议国内服务器部署，可能会被封。数据库和Redis可以用国内的。面板太明显了，而且国内需要备案的域名。

能加一下吗我还有些问题需要问，在github问太麻烦了

**Comment by jonssonyan** [comment]
v2.0.5最新版已经解决图片问题
