### ISSUE TITLE
面板监听8081 8082端口目的是什么

### ISSUE THREAD

**Issue by kkksa528** [trojanpanel/install-script#184]
文档未提及监听8081 8082   为什么监听这两端口
trojan-pa 1086 root    7u  IPv6  13799      0t0  TCP *:tproxy (LISTEN)
trojan-pa 1093 root    9u  IPv6  13805      0t0  TCP *:8082 (LISTEN)

**Comment by kkksa528** [comment]
以及8888端口有独特指纹

**Comment by jonssonyan** [comment]
8082是Hysteria外部验证接入http接口监听的端口
8081是后端监听的端口
8888是前端监听的端口

**Comment by kkksa528** [comment]
那你文档得说一下，8081不开会后端会报错超时 ，8082不开hysteria能用，前端面板指纹太明显了，能用指纹扫ip和域名

**Comment by kkksa528** [comment]
有用8100端口为什么还要8081,8082

**Comment by jonssonyan** [comment]
8100是gRPC端口，不是一个类型的端口。指纹特征我看看。另外脚本里面可以随时自定义前端端口。
