### ISSUE TITLE
更新2.0.5后，面板上无法连接所有服务器，显示异常

### ISSUE THREAD

**Issue by 6396036** [trojanpanel/install-script#188]
{"level":"error","msg":"gRPC GetNodeState 异常 ip: 152.xx.xx.xx grpc port: 8100 err: rpc error: code = Unimplemented desc = unknown method GetNodeState for service ApiStateService","time":"2023-03-30 21:22:56"}
{"level":"error","msg":"gRPC GetNodeState 异常 ip: 15.xx.xx.xx grpc port: 8100 err: rpc error: code = Unimplemented desc = unknown method GetNodeState for service ApiStateService","time":"2023-03-30 21:22:56"}
{"level":"error","msg":"gRPC GetNodeServerState 异常 ip: 152.xx.xx.xx grpc port: 8100 err: rpc error: code = Unimplemented desc = unknown method GetNodeServerState for service ApiStateService","time":"2023-03-30 21:23:03"}
{"level":"error","msg":"gRPC GetNodeServerState 异常 ip: 194.xx.xx.xx grpc port: 8100 err: rpc error: code = Unimplemented desc = unknown method GetNodeServerState for service ApiStateService","time":"2023-03-30 21:23:03"}
{"level":"error","msg":"gRPC GetNodeServerState 异常 ip: 15.xx.xx.xx grpc port: 8100 err: rpc error: code = Unimplemented desc = unknown method GetNodeServerState for service ApiStateService","time":"2023-03-30 21:23:03"}
{"level":"error","msg":"gRPC GetNodeServerState 失败 ip: 103.xx.xx.xx grpc port: 8100 err: \u003cnil\u003e","time":"2023-03-30 21:23:03"}
{"level":"error","msg":"gRPC GetNodeServerState 失败 ip: 152.xx.xx.xx grpc port: 8100 err: \u003cnil\u003e","time":"2023-03-30 21:23:03"}
{"level":"error","msg":"gRPC GetNodeServerState 异常 ip: 146.xx.xx.xx grpc port: 8200 err: rpc error: code = Unavailable desc = error reading from server: EOF","time":"2023-03-30 21:23:04"}
{"level":"error","msg":"gRPC GetNodeServerState 异常 ip: 152.xx.xx.xx grpc port: 8100 err: rpc error: code = Unimplemented desc = unknown method GetNodeServerState for service ApiStateService","time":"2023-03-30 21:23:21"}

**Comment by 6396036** [comment]
补充：升级之前面板2.0.4，连接均正常。 
其他未作任何修改，仅仅是升级了面板为2.0.5

**Comment by jonssonyan** [comment]
Trojan Panel Core也一并升级，升级到v2.0.4 ,版本要对应。
