### ISSUE TITLE
安装完成以后/var/lib/docker/containers内容器每隔一个月就会增长到19G大

### ISSUE THREAD

**Issue by wangchuanyes** [trojanpanel/install-script#19]
搬瓦工服务器磁盘容量20G，没有安装任何其他服务。我都是每隔一个月重置一下系统，然后重新安装trojanpanel。请问有没有什么方便的办法解决这种情况？

**Comment by wangchuanyes** [comment]
/var/lib/docker/containers内容器每隔一个月就会增长到19G大

**Comment by jonssonyan** [comment]
实测面板运行一年的磁盘占用：9.63GB/25GB（已使用/全部），检查自己服务器原因或者DD系统后重装面板。

**Comment by wangchuanyes** [comment]
> 



> 实测面板运行一年的磁盘占用：9.63GB/25GB（已使用/全部），检查自己服务器原因或者DD系统后重装面板。

那应该是你一年用的流量还没有我半个月用的多吧。我服务器没有问题，除了trojanpanel没有安装任何其他东西，而且我标题已经写得很明白了，是/var/lib/docker/containers内的容器文件增长到将近19个G那么大，容器名字太长我就不复制过来了。是仅仅那一个容器文件就占用了这么大，问题明显出在这里，不明白我还要检查服务器干什么呢？

**Comment by wangchuanyes** [comment]
> 实测面板运行一年的磁盘占用：9.63GB/25GB（已使用/全部），检查自己服务器原因或者DD系统后重装面板。

没错我就是每个月都重置系统重新安装trojanpanel一次。这次我备份了服务器快照，下次再爆满看看直接恢复快照行不行。

**Comment by jonssonyan** [comment]
如果一定是tp原因，猜测是系统日志太多了，因为这些日志都是一些正常的系统运行日志，下个版本会对日志容器进行控制。临时解决办法如下：

1. 删除日志文件

脚本如下：
```shell
#!/bin/bash
logs=$(find /var/lib/docker/containers/ -name *-json.log)

for log in $logs
  do
    echo "clean logs : $log"
    cat /dev/null > $log
done
```

假如脚本文件名称为 `clean.sh` 那么执行脚本的命令为：`chmod +x clean.sh && ./clean.sh`

通过命令：`du -d1 -h /var/lib/docker/containers | sort -h`，查看日志文件大小。最后对比一下清理日志之后可用磁盘大小。

2. 配置Docker设置最大日志文件大小。

在`/etc/docker/daemon.json`文件中增加如下内容。

```json
{
    "log-driver":"json-file",
    "log-opts":{
        "max-size" :"50m","max-file":"3"
    }
}
```

参数解释：

- max-size=50m：一个容器日志大小上限是50M。
- max-file=3：可以存在的最大日志文件数，如果超过最大值，则会删除最旧的文件，仅在max-size设置时有效，默认值为5。

**注意：设置完之后再安装tp，此配置只对新建的容器有效，对于原有容器需要重建。**

尝试以上两种方法，观察一下磁盘下个月是否爆满。推荐执行清理脚本，效果立竿见影，另外可以写个定时任务，每个月调一次脚本清理一下。如果磁盘空间下去了，可能真就是日志太多的问题，下个版本会修复。

**Comment by wangchuanyes** [comment]
> 如果一定是tp原因，猜测是系统日志太多了，但是这些日志都是一些正常的系统运行日志，所以只能说猜测。临时解决办法如下：
> 
> 1. 删除日志文件
> 
> 脚本如下：
> 
> ```shell
> #!/bin/bash
> logs=$(find /var/lib/docker/containers/ -name *-json.log)
> 
> for log in $logs
>   do
>     echo "clean logs : $log"
>     cat /dev/null > $log
> done
> ```
> 
> 假如脚本文件名称为 `clean.sh` 那么执行脚本的命令为：`chmod +x clean.sh && ./clean.sh`
> 
> 通过命令：`du -d1 -h /var/lib/docker/containers | sort -h`，查看日志文件大小。最后对比一下清理日志前后可用磁盘大小。
> 
> 2. 配置Docker设置最大日志文件大小。
> 
> 在`/etc/docker/daemon.json`文件中增加如下内容。
> 
> ```json
> {
>     "log-driver":"json-file",
>     "log-opts":{
>         "max-size" :"50m","max-file":"3"
>     }
> }
> ```
> 
> 参数解释：
> 
> * max-size=50m：一个容器日志大小上限是50M。
> * max-file=3：可以存在的最大日志文件数，如果超过最大值，则会删除最旧的文件，仅在max-size设置时有效，默认值为5。
> 
> **注意：设置完之后再安装tp，此配置只对新建的容器有效，对于原有容器需要重建。**
> 
> 脚本已更新，把方案2整合到了脚本里面（ [3240b8e](https://github.com/trojanpanel/install-script/commit/3240b8e2c3116927fda215acf3b10a5007b8e61e) )，不嫌麻烦可以用最新脚本重装系统和tp。

好的 万分感谢
