### ISSUE TITLE
caddy安装失败

### ISSUE THREAD

**Issue by wakaka-sam** [trojanpanel/install-script#190]
![image](https://user-images.githubusercontent.com/49387188/229016811-3139d6c7-93e8-4515-9204-f3315ce78c96.png)
本地安装了宝塔，宝塔应该占了80，443端口，因此安装的时候选了800端口。用root权限进行安装的。  
对后端这一套不太熟，感谢各路大佬帮忙看看

**Comment by wakaka-sam** [comment]
补充：本地有使用nginx做代理

**Comment by jonssonyan** [comment]
现在caddy的端口可以自定义，如果有冲突可以换端口，你运行一键安装脚本输入故障检测，看看caddy报的什么错

**Comment by wakaka-sam** [comment]
![image](https://user-images.githubusercontent.com/49387188/229453993-68aba9e0-3780-4cbc-b330-020cf74d4ac1.png)
我手动装caddy试试

**Comment by jonssonyan** [comment]
按理说现在caddy可以自定义端口，即使80被占用也不影响trojan panel的搭建，互不影响的。

**Comment by wfniub** [comment]
似乎无法使用非80端口！

**Comment by jonssonyan** [comment]
如果用Caddy2自动申请证书就要先把80端口应用暂停，腾出80端口用于申请证书，否则自备证书
