### ISSUE TITLE
如何对接其他服务器呢？

### ISSUE THREAD

**Issue by gogogojason** [trojanpanel/install-script#192]
多台服务器接入到平台如何实现？这个功能能够开发，比如我在其他服务器上装入后端，用这个平台前端接入

**Comment by jonssonyan** [comment]
节点服务器装一次trojan panel core，面板服务器使用服务器管理的功能将节点服务器信息填上，之后就可以在节点管理随意在远程节点服务器上管理节点了。

**Comment by jonssonyan** [comment]
之前发的视频教程：https://www.youtube.com/watch?v=He4hcLItxSw&list=PLSrfdI4k7D50SCxqR873hCzhimEstcdtJ
