### ISSUE TITLE
升级2023.03.31穷奇后 已存在的服务器配置和账号 全部显示异常

### ISSUE THREAD

**Issue by AKGO47** [trojanpanel/install-script#193]
从2022.12.29 麒麟升级上来
先升级的面板 再升级的core
所有已存在的服务器配置和账号配置 全部显示异常
防火墙仅开9507、8100、6378
请问新版本 是否有其他端口需要开放 而导致的监测异常呢？

**Comment by jonssonyan** [comment]
新版没有其他端口需要开放，你看下节点能不能用，然后注销重新登陆或者重启服务器试试。

**Comment by AKGO47** [comment]
我回滚了服务器，再次重新安装，服务器和账号配置都显示正常了，感谢你的项目。
