### ISSUE TITLE
博主可以写一个服务器联机添加节点的教程么。

### ISSUE THREAD

**Issue by nameoyiyou** [trojanpanel/install-script#198]
开发者，您好，最近我使用了您的项目，发现两台服务器联机连接不上，提示服务器异常，（防火墙啥的都没问题，8100已经放开），请您，出一个对接教程吧，我们好根据您的教程进行排错

**Comment by jonssonyan** [comment]
之前youtube发过视频，但是版本比较老了，不过也具有参考作用，可以试试。https://www.youtube.com/watch?v=He4hcLItxSw&list=PLSrfdI4k7D50SCxqR873hCzhimEstcdtJ

**Comment by Mrered** [comment]
新版本的使用逻辑有一定变化，可以麻烦 @jonssonyan  再录制一个新视频教程嘛？

我在第二个服务器上确认无误填了对的 IP 、端口和数据库密码（都是第一个服务器上的值），但是查看 trojan-panel-core 容器状态时，一直是重启中，去容器日志查看，什么内容都没有。求助！
