### ISSUE TITLE
502的错误像是一个bug

### ISSUE THREAD

**Issue by AD696** [trojanpanel/install-script#199]
![1680766102299](https://user-images.githubusercontent.com/127026717/230305597-1771d7ab-ec61-457f-ad54-1e1522e67726.jpg)
后台登录报502错误，u22系统是直接无法安装re，cos安装好之后报502

**Comment by AD696** [comment]
<img width="1026" alt="WeChat2d2a521ce26ca682719bfecb6232c80e" src="https://user-images.githubusercontent.com/127026717/230307852-006dc51b-3c75-4e82-864b-1f35d7e2a95e.png">

**Comment by AD696** [comment]
---> Trojan Panel后端运行异常 日志如下：
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:37:50"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:38:50"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:39:50"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:40:50"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:41:50"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:42:51"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:43:51"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:44:51"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:45:51"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:46:52"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:47:52"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:48:52"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:49:52"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:50:53"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:51:53"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:52:53"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:53:53"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:54:54"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:55:54"}
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-04-06 15:56:54"}

**Comment by jonssonyan** [comment]
502的原因是后端和数据库之间连接出现了问题，配合谷歌排查一下。
