### ISSUE TITLE
可否让后端能在128M内存的小鸡运行。让nat垃圾发挥一下余热

### ISSUE THREAD

**Issue by MechanicF** [trojanpanel/install-script#200]
可否让后端能在128M内存的小鸡运行。让nat垃圾发挥一下余热

**Comment by jonssonyan** [comment]
128M太小了，512M勉强可以，看下性能测试。https://trojanpanel.github.io/tutorial/performance-testing.html

**Comment by MechanicF** [comment]
那看来只能挂探针了。还以为能发挥余热来着。128M docker都装不上
