### ISSUE TITLE
Unable to import accounts

### ISSUE THREAD

**Issue by versuos** [trojanpanel/install-script#203]
When i import accounts backup, show me header error.

**Comment by jonssonyan** [comment]
This is a compatibility issue. I have no problem testing on office2010, but there will be problems in testing on office2016. This problem will be fixed in later versions.

**Comment by jonssonyan** [comment]
Or use json format to import and there will be no compatibility issues everywhere.

**Comment by jonssonyan** [comment]
try v2.1.0
