### ISSUE TITLE
服务器列表应该填啥呀

### ISSUE THREAD

**Issue by panzx1222** [trojanpanel/install-script#205]
我输入了VPS的服务器IP。但是显示是异常，实际上SSH可以正常链接

**Comment by jonssonyan** [comment]
看一下防火墙有没有放行对应的api端口，api端口在添加服务器的时候会让你填

**Comment by jonssonyan** [comment]
https://github.com/trojanpanel/install-script/issues/163

**Comment by kisnows** [comment]
> https://github.com/trojanpanel/install-script/issues/163

issue 已经被删除了，目前找不到添加第二台服务器的方法。 我已经安装了 core，但是添加的时候还是显示异常。

**Comment by jonssonyan** [comment]
@kisnows 忘了为什么删了，印象里面我好像没删除过issue。。添加第二台服务器和第一台一样的操作，几乎没有区别，服务器地址填IP

**Comment by kisnows** [comment]
现在碰到的问题是第二台服务器已经安装了 core，并且端口也是正常开放的。
但是在主服务面板那边点击添加，显示是异常
________________________________
发件人: jonssonyan ***@***.***>
发送时间: 2024年1月18日 0:52
收件人: trojanpanel/install-script ***@***.***>
抄送: 抹桥 ***@***.***>; Mention ***@***.***>
主题: Re: [trojanpanel/install-script] 服务器列表应该填啥呀 (Issue #205)


@kisnows<https://github.com/kisnows> 忘了为什么删了，印象里面我好像没删除过issue。。添加第二台服务器和第一台一样的操作，几乎没有区别，服务器地址填IP

―
