### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Hosein-msv** [trojanpanel/install-script#206]
Hi,
Today, I updated the panel and the panel core to the latest version, but after that it does not enter the node section and gives this error :
System error, please contact the system administrator
While on the first page of the panel, there is the number of nodes
![node 2](https://user-images.githubusercontent.com/119467369/232181356-63299014-3f35-4e7e-bf14-d5f7aa106ccb.jpg)

Also, when I want to output from users, it gives this error :
Permission denied
I am sure that I logged in with the admin account and did everything correctly...
Thank you for your help to solve the problem.
![error](https://user-images.githubusercontent.com/119467369/232180077-99730bf3-f328-40b3-8a28-3b3d69d7aadd.jpg)
![log](https://user-images.githubusercontent.com/119467369/232180191-0e9b4475-92b7-4a59-a051-012d0c3c4cb9.jpg)

**Comment by jonssonyan** [comment]
If you look at the log, your database field is missing. Check if there is a problem with your database, or your database may have been invaded.
