### ISSUE TITLE
关于安装最新穷奇2.0后，添加服务器显示异常问题，解决办法

### ISSUE THREAD

**Issue by shuaibb521** [trojanpanel/install-script#208]
我自己测试下来，运行脚本后，在输入ip的地方不要敲回车选择默认， 要直接输入ip，搭建完毕后，即可正常添加服务器

**Comment by shuaibb521** [comment]
无论是面板还是面板核心，都这样操作，

**Comment by jonssonyan** [comment]
你搭建的是tp和tp core在一台服务器上面还是分布在多台服务器？如果是一台服务器，应该是你服务器的问题。我测试过很多次，直接回车默认是本机127.0.0.1是可以正常使用的。如果是多台服务器就应该输入远程服务器的IP地址，文档上有说明。你可以在看看

**Comment by shuaibb521** [comment]
一台服务器上，我自己手里阿里云跟腾讯云服务器都是这个问题
