### ISSUE TITLE
联机版添加服务器显示异常

### ISSUE THREAD

**Issue by Eternallyl** [trojanpanel/install-script#213]
新开一个vps后，tp上添加服务器显示异常
【防火墙、端口均已开放】

**Comment by xiaopan369** [comment]
我也是这样

**Comment by jonssonyan** [comment]
https://github.com/trojanpanel/install-script/issues/163

**Comment by xiziqiwuyou** [comment]
同样出现此问题，忘大佬能提供帮助  

最新版：Trojan Panel内核(trojan-panel-core)当前版本为 v2.1.1 最新版本为 v2.1.1
日志输出：{"level":"error","msg":"gRPC GetNodeServerState 失败 ip: xxxx grpc port: 8100 err: \u003cnil\u003e","time":"2023-07-07 01:11:04"}
{"level":"error","msg":"gRPC GetNodeServerState 失败 ip: xxxx grpc port: 8100 err: \u003cnil\u003e","time":"2023-07-07 01:11:15"}
添加本机服务器正常，添加其他服务器显示异常，无法获取到TP Core版本。
如果尝试添加节点的话，会直接注销掉此前端，且后端输出同样日志。
