### ISSUE TITLE
windows clash无法连接Trojan节点；有可能是BUG，用官方最新版本的服务器配置Trojan节点，windows clash也不能连接；能不能麻烦你们排查看看；

### ISSUE THREAD

**Issue by sycccn** [trojanpanel/install-script#219]
windows clash无法连接Trojan节点；有可能是BUG，用官方最新版本的服务器配置Trojan节点，windows clash也不能连接；能不能麻烦你们排查看看；

**Comment by jonssonyan** [comment]
更新了v2.1.0 试试

**Comment by sycccn** [comment]
测试OK了；




*****************************************************
江苏欧迈科技有限公司
Jiangsu Omai Technology Co.,LTD.
地址：苏州吴中区郭巷蓝文化大厦6F
移动电话：13306208288
联系人：郑书春  
***@***.***
电话:0512-87815019
URL：www.it-jt.cn
*****************************************************
 
发件人： jonssonyan
发送时间： 2023-05-04 21:28
收件人： trojanpanel/install-script
抄送： sycccn; Author
主题： Re: [trojanpanel/install-script] windows clash无法连接Trojan节点；有可能是BUG，用官方最新版本的服务器配置Trojan节点，windows clash也不能连接；能不能麻烦你们排查看看； (Issue #219)
更新了v2.1.0 试试
