### ISSUE TITLE
获取公钥和私钥

### ISSUE THREAD

**Issue by Ramintn** [trojanpanel/install-script#220]
现实中公私钥在哪里找？
以及在哪里可以找到短 ID？ 和服务器名称？

**Comment by jonssonyan** [comment]
./xray x25519 生成
shortIds填空字符串
serverNames填域名
参考：https://xtls.github.io/config/transport.html#realityobject

**Comment by Ramintn** [comment]
谢谢，但是当我运行命令“./xray x25519”时，我得到了错误“没有这样的文件或目录”并且也不能将“shortid”留空，因为它是必填字段，
