### ISSUE TITLE
接口请求时间

### ISSUE THREAD

**Issue by Eternallyl** [trojanpanel/install-script#221]
可不可以把服务器列表和节点列表的状态采用异步方式去检测，现在的列表如果有2+异常就很慢，再加上5s自动取消请求的机制，会导致整个列表加载不出来

**Comment by ryyyzer** [comment]
我加了3个服务器开了5个节点 服务器偶尔能加载出来 节点刚添加完没十分钟就永远都是timeout了

**Comment by jonssonyan** [comment]
后端异步并发处理了，前端异步会导致接口请求太多。
