### ISSUE TITLE
原版 trojan-go 存在开启 websocket 之后通过 api 添加用户不生效的 bug，建议更新

### ISSUE THREAD

**Issue by Seazonx** [trojanpanel/install-script#227]
原版 trojan-go 存在开启 websocket 之后通过 api 添加用户不生效的 bug
所以导致这边的 trojan-go 节点如果开启WS，也是无法使用的
详情见：
https://github.com/p4gefau1t/trojan-go/issues/345

建议更新 trojan-go 至这个fork版本

https://github.com/fregie/trojan-go

**Comment by jonssonyan** [comment]
先用Xray的Trojan吧，已经收到好几个版本的trojango fork版本建议，还没有确定主流版本。
