### ISSUE TITLE
Caddy安装失败,是和宝塔冲突么？有解决方案没？

### ISSUE THREAD

**Issue by skyfly2000** [trojanpanel/install-script#24]
请教：Caddy安装失败,是和宝塔冲突么？有解决方案没？
80端口被占用……有点懵……

-bash: kill: 274119
445926
445927: arguments must be process or job IDs
1.0.5: Pulling from teddysun/caddy
Digest: sha256:10b4950a23bb564659dd4ab4c3fbcb3bb6d9a7303f8ce62cdeb060b3caf530d1
Status: Image is up to date for teddysun/caddy:1.0.5
docker.io/teddysun/caddy:1.0.5
d4ef536bc6748a4b46ff74f42ea6e28416bbb2e24cae49d81b0d4557455d7042
docker: Error response from daemon: driver failed programming external connectivity on endpoint trojan-panel-caddy (53c552b763890a044fcf53eec15316c198c0525be1668dc5b77384aef2acc9bd): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use.
---> Caddy安装失败

连接丢失,正在尝试重新连接!
Activate the web console with: systemctl enable --now cockpit.socket

Last failed login: Wed Oct 12 19:07:51 CST 2022 from 179.43.140.150 on ssh:notty
There were 20 failed login attempts since the last successful login.
Last login: Wed Oct 12 19:04:45 2022 from 127.0.0.1
[root@VM-32-12-centos ~]# docker ps -a
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS    PORTS     NAMES
d4ef536bc674   teddysun/caddy:1.0.5   "/usr/bin/caddy -con…"   15 seconds ago   Created             trojan-panel-caddy

**Comment by skyfly2000** [comment]
删除d4ef536bc674容器依然不行…………

**Comment by skyfly2000** [comment]
@jonssonyan 大佬看到帮忙解决一下，谢

**Comment by skyfly2000** [comment]
@jonssonyan 大佬看到帮助解决。谢！

**Comment by jonssonyan** [comment]
目前脚本里面Caddy是80（不可以自定义），Caddy转发端口（默认8863）可以自定义。如果需要自定义Caddy端口，这个涉及到TroajnGo和Xray的回落端口设置，这个版本是满足不了了，等v1.2版本吧，在开发了。

**Comment by jonssonyan** [comment]
方案两个，1. 改Caddy端口，2. 改宝塔端口。Caddy的端口是TrojanGo和Xray的回落端口，最好是80，一般Web网站默认都是80，其他端口会感觉很奇怪，如果改成其他端口，可能会导致稳定性降低。

**Comment by skyfly2000** [comment]
@jonssonyan 谢了！
