### ISSUE TITLE
timeout of 5000ms exceeded 超时问题

### ISSUE THREAD

**Issue by cuiyanjie** [trojanpanel/install-script#240]
自动脚本安装后一段时间就会出现timeout of 5000ms exceeded问题，无法登录，域名和ip登录都不行，但生成的节点可用，ssh可访问，找不到修改超时的文件。最近两个新版本才会出现的问题，之前的版本不会。

**Comment by jonssonyan** [comment]
重装或者回退到旧版本

**Comment by cuiyanjie** [comment]
每次重装过一段时间，就会这样，不知道为啥。

**Comment by jonssonyan** [comment]
应该是网络问题。
