### ISSUE TITLE
可以添加多域名，并申请https证书吗？

### ISSUE THREAD

**Issue by FLIER001** [trojanpanel/install-script#241]
> 翻了doc，没找到相关的说明

我给IPV4和IPV6分别设置了不同的域名，然而部署naiveproxy的时候，只能连上安装面板时选择的域名

原因是openwrt和mac官方客户端无法使用类似`sni`和`skip-certs-verify`等参数，必须服务器安装了对应的https证书才可以连接成功

希望求支持

**Comment by jonssonyan** [comment]
目前只支持单个域名。
