### ISSUE TITLE
大佬有计划开发自定义重置流量时间的功能吗

### ISSUE THREAD

**Issue by maomaochong1574** [trojanpanel/install-script#242]
大佬有计划开发自定义重置流量时间的功能吗

**Comment by jonssonyan** [comment]
现在系统设置里面有每月重设流量的选项，你想几号重设

**Comment by maomaochong1574** [comment]
我三个节点的VPS流量重置时间不一样，都不是1号，可以各重置各的吗

**Comment by jonssonyan** [comment]
流量重设指的是账户的流量重设。比如账户A，这个月用了10G，下个月1号使用过的流量变为0

**Comment by maomaochong1574** [comment]
好的，流量重置我理解的有一些偏差，那服务器列表里面可以增加vps的流量统计和重置流量时间吗，监控一下vps的流量使用状态，防止超标

**Comment by jonssonyan** [comment]
vps流量监控在其他issue提了，这个先关了。

**Comment by Mrered** [comment]
> vps流量监控在其他issue提了，这个先关了。

请问这个在哪个 issue 里？

我现在的使用需求是，机器的流量每月 1 号重置，但是我发现用户的流量好像不是每月 1 号重置的？另外，我和朋友组的几台机器的流量是每月限量的，我们几个人也希望彼此的每月用量有个上限，所以需要分别限制机器的流量和用户的流量，这个目前还没发现在哪可以设置。

感谢作者！

Which issue is this in?

My current usage requirement is that the machine's traffic resets on the 1st of each month, but I found that the user's traffic does not seem to reset on the 1st of each month? In addition, several machines in my friend group have monthly limits on traffic, and we also hope to set an upper limit on each other's monthly usage. Therefore, it is necessary to restrict the traffic of machines and users separately. I have not yet found where this can be set.

Thank you owner!

**Comment by jonssonyan** [comment]
@Mrered https://github.com/trojanpanel/install-script/issues/212
