### ISSUE TITLE
大佬有计划开发用户权限相关的模块吗

### ISSUE THREAD

**Issue by maomaochong1574** [trojanpanel/install-script#243]
有计划开发用户权限相关的模块吗，比如用户只能看到特定的节点，目前貌似是只要剪了账户就能看到所有的节点

**Comment by sycccn1** [comment]
一样的需求

**Comment by jonssonyan** [comment]
目前没计划

**Comment by CamaroW** [comment]
@maomaochong1574 等着你自己开发了，不是刚刚开源吗，我虽然是个小白但感觉这个功能应该不难，加油哈哈哈哈
