### ISSUE TITLE
建议添加中转功能

### ISSUE THREAD

**Issue by Slinging** [trojanpanel/install-script#245]
大致的连接顺序就是用户本地->gfw->vps中转->vps落地。
有时候vps的一些特点对于用户来说十分重要。比如ip十分纯净，用来运营tk，或者流媒体解锁等。但是这类vps多半没有大陆优化线路，或者被墙。总之访问速度十分慢，所以需要一台到用户本地和落地服务器连接速度都优秀的vps进行中转服务。
中转服务器与用户本地之间的连接协议，用目前面板上的协议就可以。而中转服务器到落地服务器之间的协议就可以用一些简单的协议，比如ss，甚至socks5。
（当然，构建隧道更好，不过代码更复杂）

**Comment by jonssonyan** [comment]
xray ss协议可以做中转，已经有人实践了。
