### ISSUE TITLE
如何将分布式安装后不同机器用到的端口反向代理，供其他机器连接？

### ISSUE THREAD

**Issue by Mrered** [trojanpanel/install-script#247]
刚刚看完作者发布的新教程了，有一个小问题：

我可以用Nginx Proxy Manager（下称NPM🐶）将分布式部署时用到的端口进行反代吗？如果NPM不能操作，可以用其他方式实现吗？

另外，目前我只成功将面板反代出来，在反代数据库机器上的端口，后端机器上的端口，内核机器上的端口时都失败了。

因为NPM只支持反代http/https，不知道数据库后端内核之间调用用的http还是tcp。如果是tcp就不能用NPM反代了。目前我只会用NPM反代，Nginx或者Caddy的配置文件都不会写，求教！感谢🥹！

**Comment by jonssonyan** [comment]
前端后端是http/https，数据库/Redis是TCP，内核里面管理的是代理软件，代理软件的端口有TPC/UDP的。
可以用ChatGPT写Nginx文件，我试过准确率还是很高的。
