### ISSUE TITLE
膜拜大佬,,请问支持设备数限制也就是IP数限制吗?,Xray是开放了API的.

### ISSUE THREAD

**Issue by GitH123i** [trojanpanel/install-script#248]
Xray/Hysteria/NaiveProxy,其他不知道,Xray是开放了API的.

**Comment by jonssonyan** [comment]
就算Xray支持，hysteria naiveproxy trojango（有Bug）也不支持，不做到统一，功能做就没意义。
这个问题我举个例子，你设置3个设备数，Xray支持那么这个用户就只能3个ip连接Xray节点，但是hysteria naiveproxy trojango可以随便连。
