### ISSUE TITLE
从2023.03.31穷奇升级到2.1.5报502错误

### ISSUE THREAD

**Issue by AKGO47** [trojanpanel/install-script#249]
当前安装的是2023.03.31穷奇
联机版本
1：先升级core （先升级了两台 然后发现升级后的机器 无法翻）
![企业微信截图_20230606110302](https://github.com/trojanpanel/install-script/assets/24536534/2c443715-1e20-4eaf-a268-3e5d324980b2)
2：管理机器 先升级core 再升级panel 打开管理界面 报502错误 并且无法登录
![企业微信截图_20230606105053](https://github.com/trojanpanel/install-script/assets/24536534/89510fe5-6651-44a1-835f-55ad00b1effa)

麻烦大佬指导一下
如何从2023.03.31穷奇升级到最新的2.1.5

**Comment by Duke-li** [comment]
同样遇到这个问题，不知道怎么办，求助

**Comment by jonssonyan** [comment]
根据提供的信息无法判断原因，贴一下日志。

**Comment by RnJ4** [comment]
account表要加一列last_login_time，类型为bigint。这个真的是很不专业啊😅，改表这种大变化，更新时既没有自动处理，又没有提醒，不管兼不兼容直接就升

**Comment by AKGO47** [comment]
> 根据提供的信息无法判断原因，贴一下日志。

还需要日志吗？
都需要哪些路径下的日志？我帮你复现一遍

**Comment by jonssonyan** [comment]
> > 根据提供的信息无法判断原因，贴一下日志。
> 
> 还需要日志吗？ 都需要哪些路径下的日志？我帮你复现一遍

一键脚本里面查日志的选项

**Comment by jonssonyan** [comment]
> 

https://github.com/trojanpanel/install-script/blob/ff70d15528188c787b5076f276e4ba53bceff13a/install_script.sh#L111

**Comment by AKGO47** [comment]
> > > 根据提供的信息无法判断原因，贴一下日志。
> > 
> > 
> > 还需要日志吗？ 都需要哪些路径下的日志？我帮你复现一遍
> 
> 一键脚本里面查日志的选项

在管理主机上升级到2.1.7 
先升级core 再升级面板
询问时候安装caddy 都选择的不安装

面板日志如下
{"level":"error","msg":"数据库连接异常 err: dial tcp 127.0.0.1:9507: connect: connection refused","time":"2023-06-12 04:00:16"}
{"level":"error","msg":"数据库连接异常 err: dial tcp 127.0.0.1:9507: connect: connection refused","time":"2023-06-12 04:00:17"}
{"level":"error","msg":"数据库连接异常 err: dial tcp 127.0.0.1:9507: connect: connection refused","time":"2023-06-13 04:00:19"}
{"level":"error","msg":"数据库连接异常 err: dial tcp 127.0.0.1:9507: connect: connection refused","time":"2023-06-13 04:00:20"}
{"level":"error","msg":"数据库连接异常 err: dial tcp 127.0.0.1:9507: connect: connection refused","time":"2023-06-13 04:00:20"}
{"level":"error","msg":"数据库连接异常 err: dial tcp 127.0.0.1:9507: connect: connection refused","time":"2023-06-14 04:00:16"}
{"level":"error","msg":"数据库连接异常 err: dial tcp 127.0.0.1:9507: connect: connection refused","time":"2023-06-14 04:00:16"}
{"level":"error","msg":"数据库连接异常 err: dial tcp 127.0.0.1:9507: connect: connection refused","time":"2023-06-14 04:00:17"}
{"level":"error","msg":"数据库连接异常 err: dial tcp 127.0.0.1:9507: connect: connection refused","time":"2023-06-14 10:19:08"}
{"level":"error","msg":"数据库连接异常 err: dial tcp 127.0.0.1:9507: connect: connection refused","time":"2023-06-14 10:19:08"}
{"level":"error","msg":"数据库连接异常 err: dial tcp :0: connect: connection refused","time":"2023-06-14 10:20:48"}
{"level":"error","msg":"数据库连接异常 err: dial tcp :0: connect: connection refused","time":"2023-06-14 10:20:48"}
{"level":"error","msg":"数据库连接异常 err: dial tcp :0: connect: connection refused","time":"2023-06-14 10:20:49"}
{"level":"error","msg":"数据库连接异常 err: dial tcp :0: connect: connection refused","time":"2023-06-14 10:20:49"}
{"level":"error","msg":"数据库连接异常 err: dial tcp :0: connect: connection refused","time":"2023-06-14 10:20:50"}
{"level":"error","msg":"数据库连接异常 err: dial tcp :0: connect: connection refused","time":"2023-06-14 10:20:52"}
{"level":"error","msg":"数据库连接异常 err: dial tcp :0: connect: connection refused","time":"2023-06-14 10:20:55"}
{"level":"error","msg":"数据库连接异常 err: dial tcp :0: connect: connection refused","time":"2023-06-14 10:21:02"}


内核日志如下：
{"level":"error","msg":"naiveproxy list users http request err: Get \"http://127.0.0.1:40008/config/apps/http/servers/srv0/routes/0/handle/0/routes/0/handle/\": dial tcp 127.0.0.1:40008: connect: connection refused","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"NaiveProxy调用api添加用户错误 err: 系统错误,请联系统管理员","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"naiveproxy list users http request err: Get \"http://127.0.0.1:40009/config/apps/http/servers/srv0/routes/0/handle/0/routes/0/handle/\": dial tcp 127.0.0.1:40009: connect: connection refused","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"NaiveProxy调用api添加用户错误 err: 系统错误,请联系统管理员","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"naiveproxy list users http request err: Get \"http://127.0.0.1:40011/config/apps/http/servers/srv0/routes/0/handle/0/routes/0/handle/\": dial tcp 127.0.0.1:40011: connect: connection refused","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"NaiveProxy调用api添加用户错误 err: 系统错误,请联系统管理员","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"naiveproxy list users http request err: Get \"http://127.0.0.1:40014/config/apps/http/servers/srv0/routes/0/handle/0/routes/0/handle/\": dial tcp 127.0.0.1:40014: connect: connection refused","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"NaiveProxy调用api添加用户错误 err: 系统错误,请联系统管理员","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"naiveproxy list users http request err: Get \"http://127.0.0.1:40000/config/apps/http/servers/srv0/routes/0/handle/0/routes/0/handle/\": dial tcp 127.0.0.1:40000: connect: connection refused","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"NaiveProxy调用api添加用户错误 err: 系统错误,请联系统管理员","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"naiveproxy list users http request err: Get \"http://127.0.0.1:40005/config/apps/http/servers/srv0/routes/0/handle/0/routes/0/handle/\": dial tcp 127.0.0.1:40005: connect: connection refused","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"NaiveProxy调用api添加用户错误 err: 系统错误,请联系统管理员","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"naiveproxy list users http request err: Get \"http://127.0.0.1:40007/config/apps/http/servers/srv0/routes/0/handle/0/routes/0/handle/\": dial tcp 127.0.0.1:40007: connect: connection refused","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"NaiveProxy调用api添加用户错误 err: 系统错误,请联系统管理员","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"naiveproxy list users http request err: Get \"http://127.0.0.1:40013/config/apps/http/servers/srv0/routes/0/handle/0/routes/0/handle/\": dial tcp 127.0.0.1:40013: connect: connection refused","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"NaiveProxy调用api添加用户错误 err: 系统错误,请联系统管理员","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"naiveproxy list users http request err: Get \"http://127.0.0.1:40001/config/apps/http/servers/srv0/routes/0/handle/0/routes/0/handle/\": dial tcp 127.0.0.1:40001: connect: connection refused","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"NaiveProxy调用api添加用户错误 err: 系统错误,请联系统管理员","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"naiveproxy list users http request err: Get \"http://127.0.0.1:40002/config/apps/http/servers/srv0/routes/0/handle/0/routes/0/handle/\": dial tcp 127.0.0.1:40002: connect: connection refused","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"NaiveProxy调用api添加用户错误 err: 系统错误,请联系统管理员","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"naiveproxy list users http request err: Get \"http://127.0.0.1:40003/config/apps/http/servers/srv0/routes/0/handle/0/routes/0/handle/\": dial tcp 127.0.0.1:40003: connect: connection refused","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"NaiveProxy调用api添加用户错误 err: 系统错误,请联系统管理员","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"naiveproxy list users http request err: Get \"http://127.0.0.1:40010/config/apps/http/servers/srv0/routes/0/handle/0/routes/0/handle/\": dial tcp 127.0.0.1:40010: connect: connection refused","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"NaiveProxy调用api添加用户错误 err: 系统错误,请联系统管理员","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"naiveproxy list users http request err: Get \"http://127.0.0.1:40015/config/apps/http/servers/srv0/routes/0/handle/0/routes/0/handle/\": dial tcp 127.0.0.1:40015: connect: connection refused","time":"2023-06-14 10:21:35"}
{"level":"error","msg":"NaiveProxy调用api添加用户错误 err: 系统错误,请联系统管理员","time":"2023-06-14 10:21:35"}

**Comment by jonssonyan** [comment]
@AKGO47 DD系统重新搭建一下

**Comment by calmwang9** [comment]
遇见了同样的问题，只能重装了吗，上次版本升级也遇见类似的问题，每次升级都要重装😂

**Comment by jonssonyan** [comment]
网络问题，日志里面显示的都是通信异常。

**Comment by jonssonyan** [comment]
@AKGO47 日志里面显示，数据库连接不上会影响使用，API没调通大部分情况下没关系，应为是几秒就调一次，只要有一次通了就可以，轮询的。账号可以导入和导出，配置要自己去服务器把文件Copy下来。搭建好之后上传。配置文件路径，文档里面写了，如果没找到，就趴一下脚本里面的代码，里面有宿主机映射到容器的路径。
