### ISSUE TITLE
cdn problem

### ISSUE THREAD

**Issue by hadi-dindar** [trojanpanel/install-script#25]
after enable proxy in cdn cloudflare  and  ping my domain ( my ip changes to cloudflare )
but i cant connect to web pannel and  server .  its not work with cdn !!
how i can solve this

**Comment by jonssonyan** [comment]
v1.2.0支持自定义前端端口，安装Trojan Panel v1.2.0，然后使用cloudflare允许的端口

**Comment by FarzinFarzaneh** [comment]
I did exactly as you told :
in CloudFlare : SSL is Full
and the ports are open by cloudflare the trojan panel admin panel is ok but all the server status in Node List is giving Timeout and in Chrome it gives me ERR_SSL_PROTOCOL_ERROR
