### ISSUE TITLE
【bug】用户使用的流量不会统计，只会归为管理员的流量

### ISSUE THREAD

**Issue by mikuh** [trojanpanel/install-script#250]
![1686050069906](https://user-images.githubusercontent.com/16199680/243676196-d3856b85-9ea4-4e51-9919-2b2a76cf7a89.png)

希望能修复这个bug，或者希望公开源码我们自己来...

_Originally posted by @bilimumu in https://github.com/trojanpanel/install-script/issues/147#issuecomment-1437228080_

**Comment by jonssonyan** [comment]
每个账户里面复制URL都是不一样的，用自己的账户里的URL使用节点，才会用自己的流量。

**Comment by mikuh** [comment]
就是用的自己的URL

**Comment by mikuh** [comment]
好像是因为有延迟...
