### ISSUE TITLE
cloudflare 使用CDN 无法访问

### ISSUE THREAD

**Issue by zhangyubushiyu** [trojanpanel/install-script#251]
之前搬瓦工被墙了重新买了一台racknerd服务器，整个安装过程也没有报错。
访问前端无响应。
申请了eu.org域名并且已经添加到cloudflare  并且开启了CND。使用ping 的方式测算域名发现解析的ip不是服务器ip ，解析到了198.18.1.15。

**Comment by jonssonyan** [comment]
[CDN教程](https://www.youtube.com/watch?v=gdXLjWqKU3I)
