### ISSUE TITLE
（中优先级）节点排序建议

### ISSUE THREAD

**Issue by kkksa528** [trojanpanel/install-script#253]
给用户一个选择节点排序规则的选项，应用于 1.显示面板 2.数据库
我的需求是按照旧到新  从上到下排序
考虑到其他人可能喜欢从新到旧 从上到下
也有人喜欢按照节点名字排序
也有人喜欢按照节点类型排序
等等
面板已经脱离个人轻量化了，每个面板都管理着一堆节点，对节点排序还是很重要的
这里排序涉及两个方面   1.面板显示排序      2.数据库排序     
两者我建议分开
TBA

**Comment by jonssonyan** [comment]
ok，我看看
