### ISSUE TITLE
用户过期问题

### ISSUE THREAD

**Issue by pelacur595** [trojanpanel/install-script#254]
比如我创建了80个用户 
其中有一个用户过期了
然后默认的一页20个用户
我一页一页翻完可能就找不到这个过期用户
我把显示调整到50个一页 第一页能找到这个用户
第二页也会找到这个用户 就会复现
![image](https://github.com/trojanpanel/install-script/assets/45810874/dd3d93e3-363d-4005-b64d-1834f7de8b29)
![image](https://github.com/trojanpanel/install-script/assets/45810874/b1ee1630-958c-4d36-bdd0-7dcc4ec77f43)
同一个客户复现两次了 序号都变了

**Comment by jonssonyan** [comment]
我看看
