### ISSUE TITLE
日志查询 Trojan Panel内核 报错

### ISSUE THREAD

**Issue by JurryFong** [trojanpanel/install-script#255]
我在添加接点的时候，报错
服务器 Centos8
最新脚本，第一次安装
Dokcer ps 显示一切都正常，面板可以打开，用户可以添加
日志如下:
{"level":"error","msg":"xray query stats err: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:38443: connect: connection refused\"","time":"2023-06-12 18:53:31"}
{"level":"error","msg":"数据库同步至Xray apiPort: 38443 查询用户失败 err: gRPC连接异常","time":"2023-06-12 18:53:31"}
{"level":"error","msg":"xray get user stats err: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:38443: connect: connection refused\"","time":"2023-06-12 18:53:33"}
{"level":"error","msg":"Xray调用api添加用户错误 err: gRPC连接异常","time":"2023-06-12 18:53:33"}
{"level":"error","msg":"xray query stats err: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:38443: connect: connection refused\"","time":"2023-06-12 18:53:41"}
{"level":"error","msg":"数据库同步至Xray apiPort: 38443 查询用户失败 err: gRPC连接异常","time":"2023-06-12 18:53:41"}
{"level":"error","msg":"xray get user stats err: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:38443: connect: connection refused\"","time":"2023-06-12 18:53:41"}
{"level":"error","msg":"Xray调用api添加用户错误 err: gRPC连接异常","time":"2023-06-12 18:53:41"}
{"level":"error","msg":"xray get user stats err: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:38443: connect: connection refused\"","time":"2023-06-12 18:53:49"}
{"level":"error","msg":"Xray调用api添加用户错误 err: gRPC连接异常","time":"2023-06-12 18:53:49"}
{"level":"error","msg":"xray query stats err: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:38443: connect: connection refused\"","time":"2023-06-12 18:53:51"}
{"level":"error","msg":"数据库同步至Xray apiPort: 38443 查询用户失败 err: gRPC连接异常","time":"2023-06-12 18:53:51"}
{"level":"error","msg":"xray get user stats err: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:38443: connect: connection refused\"","time":"2023-06-12 18:53:57"}
{"level":"error","msg":"Xray调用api添加用户错误 err: gRPC连接异常","time":"2023-06-12 18:53:57"}
{"level":"error","msg":"xray query stats err: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:38443: connect: connection refused\"","time":"2023-06-12 18:54:01"}
{"level":"error","msg":"数据库同步至Xray apiPort: 38443 查询用户失败 err: gRPC连接异常","time":"2023-06-12 18:54:01"}
{"level":"error","msg":"xray get user stats err: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:38443: connect: connection refused\"","time":"2023-06-12 18:54:05"}
{"level":"error","msg":"Xray调用api添加用户错误 err: gRPC连接异常","time":"2023-06-12 18:54:05"}
{"level":"error","msg":"trojan go get user stream err: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:32096: connect: connection refused\"","time":"2023-06-12 18:54:05"}
{"level":"error","msg":"TrojanGo调用api添加用户错误 err: gRPC连接异常","time":"2023-06-12 18:54:05"}

**Comment by JurryFong** [comment]
我是增加CF CDN接点的时候报错来着

**Comment by SchoenJoanne** [comment]
这个错误一直都有。服务器运行一段时间后就会出现。有些vps不会出现有些无论怎么调试都会

**Comment by JurryFong** [comment]
好的，感谢，我再重新搭建一下
