### ISSUE TITLE
[安装脚本][bug]caddy伪装网站

### ISSUE THREAD

**Issue by kkksa528** [trojanpanel/install-script#256]
再仅选择通过caddy申请证书时依然会下载伪装网站文件并解压部署
复现：脚本选项
运行
3.安装core----
设置伪装Web  3. 不设置----
设置证书  1. 安装Caddy 2（自动申请/续签证书）
 这时脚本会立刻部署伪装网站

**Comment by jonssonyan** [comment]
@kkksa528 Caddy可以既做伪装Web，有可以自动管理证书，功能拉满了。

**Comment by jonssonyan** [comment]
只要在安装过程中选择安装Caddy就会做伪装Web+自动管理证书，不管是在选择设置证书申请方式的时候还是选择是否设置伪装Web的时候。理论上可以分离，没做是因为Caddy配置文件太长了，会让脚本文件行数太多，维护起来麻烦。
如果你只要装web就只装nginx，不设置证书，如果你只要证书就不设置伪装Web，然后手动设置证书。
