### ISSUE TITLE
能不能取消端口100-30000的限制

### ISSUE THREAD

**Issue by guan9527b** [trojanpanel/install-script#259]
买的是NAT鸡，端口不在那范围内，没法用

**Comment by jonssonyan** [comment]
这个设置得原因是，代理软件需要暴露两个端口，一个是连接使用得端口，一个是API端口，API端口是管理代理软件的。端口范围是0~65535，系统默认端口很多是低位端口，所以从100开始，然后各分一半，防止端口冲突。或者你有什么更好的办法解决这个问题。目前你可以用Nginx或者iptables或者gost做端口转发解决Nat机器的问题。
