### ISSUE TITLE
Hysteria obfs 混淆

### ISSUE THREAD

**Issue by chidedao** [trojanpanel/install-script#26]
如题，请问这个该在哪里设置

**Comment by jonssonyan** [comment]
目前还没有支持配置这个字段，目前只有用于认证的密码。

**Comment by jonssonyan** [comment]
你具体用这个字段干什么？我在hysteria文档上看了这个字段好像也是用于做认证的。然而trojanpanel已经设置了外部验证的功能，感觉加了obs有些多余。
