### ISSUE TITLE
安装后服务器显示异常

### ISSUE THREAD

**Issue by aqlin** [trojanpanel/install-script#262]
①自动安装脚本不能连续安装前端后端和内核，选择1安装前端后不显示密码，安装后端后显示密码。
②连续安装1.2.3.4前端后端内核MariaDB后，安装NGINX时使用默认路径/root/www.google.com.crt提示找不到文件。
③采用联机版自动脚本自动安装前端后端内核后，未安装NGINX时，进入页面配置服务端时，提示服务器异常。

**Comment by jonssonyan** [comment]
1. 自动安装脚本里面 前端 后端 内核都是单独安装的，因为要兼容分布式部署
2. 服务器目录/root/www.google.com.crt没有这个文件，需要自己提前上传，我发的教程你没有好好看
3. 服务器异常要看日志
