### ISSUE TITLE
关于ip个数限制问题

### ISSUE THREAD

**Issue by flywayman** [trojanpanel/install-script#263]
请问目前trojan panel有实现ip个数限制的功能吗？
我直接修改了数据库中account表的ip_limit字段为1，但是经测试两个不同ip的设备还是能通过同一账号进行访问

**Comment by jonssonyan** [comment]
ip个数限制没做，目前数据库里面的ip个数限制和上行下行的限速字段只是预留字段。
没做的原因是面板里面集成了xray trojango naiveproxy hysteria 这四个里面大部分都没有限制ip数的API，甚至部分没有查流量的api，没办法做到统一。如果所有代理软件有几个不支持，那么这个功能做了没意义。
