### ISSUE TITLE
关于节点和端口的问题

### ISSUE THREAD

**Issue by Vinparadise** [trojanpanel/install-script#264]
感谢大佬的贡献，目前是最好的一个版本了，但是我有两个问题想问一下
关于节点设置的，目前只xray+trojan+tcp+tls才能正常用，其他组合都显示超时。是我哪里设置不对吗？shadow rocket和passwall都是一样

关于端口的问题，是不是只能用443？

**Comment by jonssonyan** [comment]
因为目前版本已经发了有一段时间了，经过很多人的测试，xray的其他组合大部分都能用，找找自己的问题。
小火箭支持是最好的，使用过的xray reality小火箭上一切正常。
没有规定端口只能用443
