### ISSUE TITLE
安卓客户端“nekobox” 使用面板“订阅链接” 丢失 “serverNames”

### ISSUE THREAD

**Issue by 123wgf** [trojanpanel/install-script#267]
<img width="541" alt="image" src="https://github.com/trojanpanel/install-script/assets/76767599/c54c956f-6821-4967-96f1-ceffa3471172">

<img width="545" alt="image" src="https://github.com/trojanpanel/install-script/assets/76767599/43e4c3f4-5692-4ca5-9b9a-1cb0721e2d3b">

![image](https://github.com/trojanpanel/install-script/assets/76767599/11d33c6b-1214-48e1-8894-9d4145fe3103)

**Comment by 123wgf** [comment]
使用nekobox，扫码功能，扫面板生成的 二维码，就能准备获取到：serverNames

**Comment by jonssonyan** [comment]
订阅链接是Clash.Meta的，不支持nekobox。
https://wiki.metacubex.one/config/proxies/vless/
![image](https://github.com/trojanpanel/install-script/assets/46235235/26ca631c-2b47-466e-abab-60f9da648147)
