### ISSUE TITLE
iOS 小火箭使用tp的meta.订阅链接的hysteria节点的问题

### ISSUE THREAD

**Issue by 202121000995** [trojanpanel/install-script#268]
ios小火箭订阅之后，所有hysteria节点，都自动加了混淆（**在节点没有设置混淆的情况下**）
<img width="378" alt="image" src="https://github.com/trojanpanel/install-script/assets/100347217/6daaf4f8-3aaf-43bd-8ed6-5a836b7d237d">

<img width="528" alt="image" src="https://github.com/trojanpanel/install-script/assets/100347217/dde92ea6-b4bd-4ffd-b95b-0176a2eac797">

**Comment by jonssonyan** [comment]
https://hysteria.network/zh/docs/uri-scheme/
小火箭的Bug
```
- obfs: Obfuscation mode (optional, empty or "xplus")
- obfsParam: Obfuscation password (optional)
```
