### ISSUE TITLE
面板装完一直连不上数据库

### ISSUE THREAD

**Issue by keving23** [trojanpanel/install-script#269]
现装mysql和redis 然后安装面板 ，面板的容器状态一直是restarting，查看日志发现
{"level":"error","msg":"数据库连接异常 err: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)","time":"2023-07-14 20:47:24"}
本机安装mysql-client 通过账号密码端口能正常连接 但是面板去连一直这个报错 是啥问题？

**Comment by jonssonyan** [comment]
确定一下密码有没有输错。之前遇到过这样的问题，原因是系统问题，装个纯净版或者换个系统就行了，比如你现在用的是CentOS，就换成Ubuntu

**Comment by keving23** [comment]
数据库密码带了#号的关系 估计不能带特殊字符
