### ISSUE TITLE
安装没有问题，检测环境也没问题，测试时候出现SSL错误

### ISSUE THREAD

**Issue by Jie-baobao** [trojanpanel/install-script#27]
连接失败https://www.google.com。发生了SSL错误，无法建立与该服务器的安全连接。

**Comment by jonssonyan** [comment]
> 连接失败[https://www.google.com。发生了SSL错误，无法建立与该服务器的安全连接。](https://www.google.com%E3%80%82%E5%8F%91%E7%94%9F%E4%BA%86SSL%E9%94%99%E8%AF%AF%EF%BC%8C%E6%97%A0%E6%B3%95%E5%BB%BA%E7%AB%8B%E4%B8%8E%E8%AF%A5%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E5%AE%89%E5%85%A8%E8%BF%9E%E6%8E%A5%E3%80%82)

这个就是Ping不通google，你检查一下服务器的网络看看

**Comment by jonssonyan** [comment]
试试最新的v1.2.0
