### ISSUE TITLE
cloudflare使用问题

### ISSUE THREAD

**Issue by zhouchengi** [trojanpanel/install-script#272]
按照[CDN教程](https://trojanpanel.github.io/tutorial/using-cdn.html)来配置的，证书申请也是正常的，使用IP可正常代理，但使用cloudflare代理的域名无法正常代理，请问可能是什么问题导致的

![image](https://github.com/trojanpanel/install-script/assets/8476106/83f82d99-4c06-4866-957f-4f715869decf)

> 同样的配置，一个是IP，一个是域名

![image](https://github.com/trojanpanel/install-script/assets/8476106/bd9095af-af7d-4c04-96e6-a973bfc052da)

> dns已解析

![image](https://github.com/trojanpanel/install-script/assets/8476106/08107499-d19d-4171-9cb7-89f7363a6ac1)

> ssl/tls已改为完全

![image](https://github.com/trojanpanel/install-script/assets/8476106/e36d4885-b6a7-4793-bedf-fb12cd412d8e)

> 证书申请好似没有问题

![image](https://github.com/trojanpanel/install-script/assets/8476106/10b0c0f9-71fa-4f93-84aa-f49f99fc2db5)

**Comment by jonssonyan** [comment]
套CDN要走WebSocket

**Comment by XLJZT** [comment]
> > 套CDN要走WebSocket
> 
> 明白了，谢谢👍

你好 能否示例一个配置学习一下 我尝试了很多次，套 cdn 的话依旧无法连接
<img width="734" alt="image" src="https://github.com/trojanpanel/install-script/assets/73268500/4ce5b404-fe6c-40e6-991a-599a10be42d8">
