### ISSUE TITLE
安装了openresty怎么代理转发到ui端口？

### ISSUE THREAD

**Issue by seancoolo1** [trojanpanel/install-script#276]
你好，我使用1pannel装的openresty本身自带nginx，安装好trojan面板后我在openresty设置了反向代理到trojan-ui的端口，证书是手动设置路径，点击网址都是显示openresty的欢迎页面，无法转到trojan-ui面板，手动输入ip：端口可以进到面板，但是是502错误，请问怎么设置让trojan panel使用openresty的代理转发？

**Comment by jonssonyan** [comment]
先装tp，tp没问题之后再装代理转发，访问不了是代理抓发配置的不对，这个问题和tp没关系。

**Comment by seancoolo1** [comment]
> 先装tp，tp没问题之后再装代理转发，访问不了是代理抓发配置的不对，这个问题和tp没关系。

大佬，目前服务器有博客，所以没法重新安装顺序，openresty是用docker装的，转发不到tp的端口，所以来询问看看怎么解决
