### ISSUE TITLE
管理其他服务器异常

### ISSUE THREAD

**Issue by Deepblue1997** [trojanpanel/install-script#279]
我有3台服务器但是只想用一个面板管理，我在主的服务器上添加其余的2台服务器一直显示异常，其他2台服务器的后端和内核也都安装了 端口8100也有启动，主服务器上telnet端口也可达，请问怎么处理呢

**Comment by Deepblue1997** [comment]
{"level":"error","msg":"gRPC GetNodeServerState err ip: x.x.x.x grpcPort: 8100 err: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp x.x.x.x:8100: connect: connection refused\"","time":"2023-08-08 10:23:12"}
{"level":"error","msg":"gRPC GetNodeServerState err ip: x.x.x.x grpcPort: 8100 err: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp x.x.x.x:8100: connect: connection refused\"","time":"2023-08-08 10:23:34"}
{"level":"error","msg":"api GetNodeServerState err ip: x.x.x.x grpcPort: 8100 err: 未认证","time":"2023-08-08 10:29:30"}

**Comment by Yuki-J1** [comment]
![image](https://github.com/trojanpanel/install-script/assets/41263770/df841247-a5ed-4136-8146-73d31b1f642a)
