### ISSUE TITLE
安装后登录界面报错Unknown column 'template_config' in 'field list'

### ISSUE THREAD

**Issue by qbyjxg** [trojanpanel/install-script#280]
你好，我刚刚安装了最新版的panel UI、后端、Core，安装成功，登录页面可以正常显示，但是随即出现了下面的报错，输入默认账号密码同样返回这个报错，请问有人知道如何解决吗？求教～
![WechatIMG1654](https://github.com/trojanpanel/install-script/assets/12605909/1d6d7231-c109-46a2-9c18-d37a937b6a7a)

**Comment by jonssonyan** [comment]
字段没了。重装看看能解决么？
