### ISSUE TITLE
VLESS+vision 

### ISSUE THREAD

**Issue by singboxone** [trojanpanel/install-script#284]
最近vision协议很有人气，和naive一样可以部分解决tls in tls 问题，并可以消除指纹特征。希望大佬可以在面板中添加这种协议

**Comment by jonssonyan** [comment]
![image](https://github.com/trojanpanel/install-script/assets/46235235/6d828a1c-9812-40b5-b281-6e082b54f37e)
realilty vision支持了啊

**Comment by singboxone** [comment]
眼瞎了.........谢谢大佬解答.........
