### ISSUE TITLE
是否能加入trojan-go-fork

### ISSUE THREAD

**Issue by Potterli20** [trojanpanel/install-script#285]
trojan-go-fork 就是更新go.mod
也更改了核心，是采用xray的
https://github.com/Potterli20/trojan-go-fork
比原版的好一点，trojan-go-fork 新增加的釆用数据库限制速度，和限制ip的功能

**Comment by jonssonyan** [comment]
这个for Star数少了，让我换TrojanGo的人很多，七嘴八舌的没有一个大部分人公认主流的fork版。先用Xray Trojan协议吧，和TrojanGo差不多。
