### ISSUE TITLE
trojan panel ui 版本号显示错误v2.1.6

### ISSUE THREAD

**Issue by whyjes** [trojanpanel/install-script#286]
trojan panel ui 版本号显示错误v2.1.6，无法更新到2.2.0
![IMG_8439](https://github.com/trojanpanel/install-script/assets/62455419/cb7e0271-259e-47b7-9c04-4f64e52bf235)

**Comment by cnlvan** [comment]
前端这次没有更新，只有后端和内核更新了，但是我更新后前端没有了。
