### ISSUE TITLE
更新最新版后，前端失效

### ISSUE THREAD

**Issue by cnlvan** [trojanpanel/install-script#287]
查询更新只有后端和内核，没有前端。8升级前端会出错自动断开，删除前端再安装也会出错，代码如下，请问什么问题啊？谢谢

---> Trojan Panel Frontend installation fails or runs abnormally, please try to repair or uninstall and reinstall

**Comment by cnlvan** [comment]
Please choose: 8
Error response from daemon: Container 5a3744a94ef18f245b2b22f0d01d3f5dc338788e5a4aff546862bd48346b9b9a is restarting, wait until the container is running
---> The current version does not support online updates

Connection closed.

**Comment by cnlvan** [comment]
Digest: sha256:0b80561e98cbf674487c4846639fc102f82ae9e533c9e3041adc52c6b28a7aab
Status: Downloaded newer image for jonssonyan/trojan-panel-ui:latest
docker.io/jonssonyan/trojan-panel-ui:latest
0e29f95521c853ce3161b08398b30ef099a52b629332c8e89131f231b720cb09
---> Trojan Panel Frontend installation fails or runs abnormally, please try to repair or uninstall and reinstall

**Comment by cnlvan** [comment]
> 1. trojan-panel-ui没有更新，最新版还是2.1.6，最近更新的是install-script、trojan-panel、trojan-panel-core我在TG频道的更新日志里面写了，注意看下。
> 2. 脚本内置的故障检测看tp前端错误原因。

我vps恢复快照了，没有错误报告了

**Comment by jonssonyan** [comment]
用到证书的应用有caddy，trojan-panel-ui，trojan-panel-core，后端不用证书。
检查/tpdata/cert里面有没有证书文件，也可以用一键安装脚本里面的故障检测也可以检测出证书申请状态是否正常。
如果第一次没有申请成功可以重启caddy或者服务器，它会重新申请。如果还是不行就换一个子域名重复以上步骤。

**Comment by cnlvan** [comment]
> 用到证书的应用有caddy，trojan-panel-ui，trojan-panel-core，后端不用证书。
> 检查/tpdata/cert里面有没有证书文件，也可以用一键安装脚本里面的故障检测也可以检测出证书申请状态是否正常。
> 如果第一次没有申请成功可以重启caddy或者服务器，它会重新申请。如果还是不行就换一个子域名重复以上步骤。

谢谢回复，今天我测试一下，升级前备份一下证书
