### ISSUE TITLE
recreate a superuser by command

### ISSUE THREAD

**Issue by agn-7** [trojanpanel/install-script#293]
I installed the trojan panel containers using docker. Unfortunately, I forgot the initial username and password that I'd created.
Is it possible to create a new superuser by command on the server or into the container?

**Comment by agn-7** [comment]
@jonssonyan 
I didn't quite catch your point!

could you please elaborate on it? how can I reset the username using the installer?

**Comment by jonssonyan** [comment]
After running the script, select option 22
![image](https://github.com/trojanpanel/install-script/assets/46235235/75e33451-4b6c-4938-a568-accc77e6f72b)

**Comment by agn-7** [comment]
@jonssonyan 
Ahh, I see. I had a problem with the installer and ZSH actually. I realized that I should use `bash <(curl -L https://github.com/trojanpanel/install-script/raw/main/install_script.sh)` instead of `source <(curl -L https://github.com/trojanpanel/install-script/raw/main/install_script.sh)`
