### ISSUE TITLE
怎么更改节点的UUID和密码

### ISSUE THREAD

**Issue by Deepblue1997** [trojanpanel/install-script#296]
想配置passwall的负载均衡需要密码和UUID一致，(2个节点创建好不一致)Xray协议，请问创建好节点后怎么改UUID和密码啊，进到/tpdata/trojan-panel-core/bin/xray/config/目录下查看配置文件也没找到密码，UUID

**Comment by jonssonyan** [comment]
不能改，根据用户名和密码生成的唯一值

**Comment by CamaroW** [comment]
@Deepblue1997 配置文件里没有密码是因为直接用的是 API 连接数据库，不走代理原本的客户端验证机制了
