### ISSUE TITLE
非443端口，无法使用

### ISSUE THREAD

**Issue by shcai** [trojanpanel/install-script#3]
不是很确定是不是因为我的端口问题，我因为443被封，所以只能使用其他端口，在安装时直接改掉了。
后台进入一切正常，生成节点的端口处按照自定义的新端口。
手机端使用的是v2rayNG, xray-core v1.5.3， 错误结果是：status!=204:400 Bad Request
电脑端V2rayN v5.16, xray-core v1.5.4, 生成的二维码导入就很奇怪，类型和地址都不太正常

**Comment by jonssonyan** [comment]
> 不是很确定是不是因为我的端口问题，我因为443被封，所以只能使用其他端口，在安装时直接改掉了。 后台进入一切正常，生成节点的端口处按照自定义的新端口。 手机端使用的是v2rayNG, xray-core v1.5.3， 错误结果是：status!=204:400 Bad Request 电脑端V2rayN v5.16, xray-core v1.5.4, 生成的二维码导入就很奇怪，类型和地址都不太正常

我尝试搭建过几次，问题不存在，请检查自己的配置。
