### ISSUE TITLE
关于近期大量vps复现Redis连接失败问题

### ISSUE THREAD

**Issue by wxj1996** [trojanpanel/install-script#302]
这是您上次给的解决方案，把Redis的最大连接数调大一点，字段是：redisMaxActive。
trojan-panel的配置文件在/tpdata/trojan-panel/config/config.ini
trojan-panel-core的配置文件在/tpdata/trojan-panel-core/config/config.ini

**Comment by wxj1996** [comment]
这两天问题比较高频，能否把连接数，默认更新到新版，不然每次只有改配置文件，或者重启服务器

**Comment by wxj1996** [comment]
我也尝试修改搭建代码     -e "redis_pass=${redis_pass}" \
        -e "redis_max_active=8" \
        -e "server_port=${trojan_panel_port}" \

**Comment by jonssonyan** [comment]
> 我也尝试修改搭建代码 定义 redis_max_active=12， 但搭建完成后，并未修改内核和后台的max_active 参数，还是默认4 -e "redis_pass=${redis_pass}" -e "redis_max_active=${redis_max_active}" -e "server_port=${trojan_panel_port}" \

运行的时候没有这个参数的，参数有默认值，是后端自动生成的。

**Comment by wxj1996** [comment]
好的非常感谢您的回复，那我还是搭建完成后，通过手动调整配置文件改大一点， 也不费事.

**Comment by wxj1996** [comment]
使用此方案，把Redis的最大连接数调大一点，字段是：redisMaxActive。
trojan-panel的配置文件在/tpdata/trojan-panel/config/config.ini
trojan-panel-core的配置文件在/tpdata/trojan-panel-core/config/config.ini
