### ISSUE TITLE
稳定半年，突然有两台服务器上的配置无法连接。

### ISSUE THREAD

**Issue by AKGO47** [trojanpanel/install-script#303]
一共3台服务器，稳定了半年，突然其中两台服务器的配置全部连不上了，3台都是NaiveProxy。使用脚本检查错误没有任何内容，重启服务器数次，依然是这两台上的配置无法连接，新建NaiveProxy也无法连接。前端面板内，服务器状态和配置状态显示绿色正常。

**Comment by jonssonyan** [comment]
排查一下端口是不是被封了，另外看后端和内核日志有没有报错
