### ISSUE TITLE
伪装站点证书更新成功，面板端口证书没有更新

### ISSUE THREAD

**Issue by bovachen** [trojanpanel/install-script#305]
你好，之前的证书到期了没有自动续期，我手动替换以后，域名:8863对应的伪装站点的证书更新成功，但是域名:8888对应的面板站点证书没有更新，请问这种情况怎么处理？

这样导致订阅链接无法使用和更新，尴尬了。

**Comment by jonssonyan** [comment]
原理上，Caddy/Nginx和前端共用的一个证书，如果更换会一起更换，浏览器开无痕模式看看，检查前端证书是不是之前更换的
