### ISSUE TITLE
一个个人需求 希望老大采纳

### ISSUE THREAD

**Issue by pelacur595** [trojanpanel/install-script#308]
之前在群有提起过
就是希望用户名支持一些符号 因为我个人是用微信号去创建的用户
有的微信号就会有— _这两种字符
导致添加不上 希望下次更新的时候 随手把这个加一下 如果工作量太大就算啦

还有另外的小请求 把群聊恢复吧  有人捣乱瞎说话就禁言 晚上就开宵禁 避免有人胡言乱语

**Comment by jonssonyan** [comment]
之前设计的时候用户名和密码规则是数字或者大小写字母，主要担心的是其他特殊字符很多，可能会存在考虑不到的情况（比如有时候眼睛看着两个字符是一样的，其实它们的md5是不一样的），会出现sql注入的问题，索性一刀切。还有建议不要用微信号关联，这种项目不合适有敏感信息。
几个月前群就禁言了，原因是我自己没有精力维护，一般很少看群（版本更新的时候会看大家的反馈，其他时候一般不看）。还有有些人瞎说话带偏一些刚进群的人，很多时候也是吹水，解决不了实际的问题，还有广告比较多。

**Comment by pelacur595** [comment]
> 之前设计的时候用户名和密码规则是数字或者大小写字母，主要担心的是其他特殊字符很多，可能会存在考虑不到的情况（比如有时候眼睛看着两个字符是一样的，其实它们的md5是不一样的），会出现sql注入的问题，索性一刀切。还有建议不要用微信号关联，这种项目不合适有敏感信息。 几个月前群就禁言了，原因是我自己没有精力维护，一般很少看群（版本更新的时候会看大家的反馈，其他时候一般不看）。还有有些人瞎说话带偏一些刚进群的人，很多时候也是吹水，解决不了实际的问题，还有广告比较多。

好吧 可能习惯了用微信号去备注  群聊乱说话的是真的该死
