### ISSUE TITLE
clash订阅地址生成有点问题

### ISSUE THREAD

**Issue by chatop2020** [trojanpanel/install-script#31]
你好，发现clash订阅地址生成有点问题，我一台域名，指定了三种类型的节点，vless,trojan,hysteria,但订阅地址中，只写入了trojan节点的信息，多服务器我还没试过，不知道会不会有同样的情况

**Comment by SKRapToR20** [comment]
> Hello, found that there is a bit of a problem with the generation of clash subscription address, I have a domain name, specify three types of nodes, vless, trojan, hysteria, but in the subscription address, only the information of the trojan node is written, multiple servers I have not tried, I don't know if there will be the same situation

did you select the row of the proxy type and the click on "clash subscribe url" ? if you do, then try reinstalling the panel .

**Comment by jonssonyan** [comment]
> 你好，发现clash订阅地址生成有点问题，我一台域名，指定了三种类型的节点，vless,trojan,hysteria,但订阅地址中，只写入了trojan节点的信息，多服务器我还没试过，不知道会不会有同样的情况

开发1.2.0版本的时候，我看了Clash的文档不支持vless和hysteria类型的节点，所以订阅地址只导出了trojan-go的，最近更新的1.3.0支持导出hysteria了（使用Clash.Meta内核），vless还需要调研一下。
