### ISSUE TITLE
status code error 500

### ISSUE THREAD

**Issue by AliRahimiiii** [trojanpanel/install-script#310]
hi,
I’ve noticed that panels frequently stop working and throw error 500 when trying to login.
rebooting the server fixes the problem, however, it can be annoying and it is something which had not happened before the last two versions.

**Comment by jonssonyan** [comment]
What errors do the logs show?

**Comment by AliRahimiiii** [comment]
![IMG_4066](https://github.com/trojanpanel/install-script/assets/32638847/99a09648-49be-48e4-8d83-fbcd6a5cbbda)

**Comment by jonssonyan** [comment]
数据库和缓存数据库连接失败了，装个纯净版系统，重新装一次看看
