### ISSUE TITLE
请问后台管理员，复制用户订阅地址提示“permission denied”应该怎么处理？

### ISSUE THREAD

**Issue by luobingwei** [trojanpanel/install-script#312]

**Comment by jonssonyan** [comment]
1. 谁搭建的系统谁是系统管理员，所以系统管理员是你而不是开发者
2. 浏览器清除缓存，重启服务器试试

**Comment by luobingwei** [comment]
> * 谁搭建的系统谁是系统管理员，所以系统管理员是你而不是开发者
> * 浏览器清除缓存，重启服务器试试

我描述不清了。是使用“sysadmin”登录后，看到所有用户的订阅地址，点击复制，会提示“permission denied”，需要换成对应用户密码登录才能复制该用户的订阅地址。

**Comment by jonssonyan** [comment]
还是权限的问题，默认系统管理员账户有最高权限。按照我说的两个方式试试看能不能解决

**Comment by luobingwei** [comment]
> 还是权限的问题，默认系统管理员账户有最高权限。按照我说的两个方式试试看能不能解决

都不行。我准备重装后台的机器重新搭建。就是担心这样导入备份的用户数据后订阅地址会发生改变。如果我重装后导入备份的用户数据，订阅地址不会发生改变意味我不用一个一个通知用户修改订阅。

**Comment by jonssonyan** [comment]
> > 还是权限的问题，默认系统管理员账户有最高权限。按照我说的两个方式试试看能不能解决
> 
> 都不行。我准备重装后台的机器重新搭建。就是担心这样导入备份的用户数据后订阅地址会发生改变。如果我重装后导入备份的用户数据，订阅地址不会发生改变意味我不用一个一个通知用户修改订阅。

重装的话再重新添加账户订阅地址会变。不过可以将用户到处，重装好之后再导入，就不会变了。

**Comment by luobingwei** [comment]
重装后解决。可惜节点要全部重新弄。

**Comment by CamaroW** [comment]
> 重装后解决。可惜节点要全部重新弄。

作者不是说可以将用户导出再导入吗，你可以试试呀。
