### ISSUE TITLE
如何在后台强制解除输错密码30分钟锁定？

### ISSUE THREAD

**Issue by StackExplode** [trojanpanel/install-script#314]
如题，前台一直有人尝试猜解密码，导致我自己正常上都上不去了，请问能否在VPS后台自行解除锁定，或者把锁定限制为输错密码的IP？

**Comment by jonssonyan** [comment]
目前密码输入错误3次锁定30分钟的功能比较简单，解决办法是清理Redis缓存就可以了，脚本里面有清理缓存的选项。

**Comment by StackExplode** [comment]
好的谢谢
