### ISSUE TITLE
HY2怎么配置？？

### ISSUE THREAD

**Issue by dscvse** [trojanpanel/install-script#315]
配置图或文件发个呗。。。我配置连不上

**Comment by jonssonyan** [comment]
https://v2.hysteria.network/zh/docs/advanced/Full-Client-Config/

**Comment by dscvse** [comment]
解决了，对了我记得你以前直播的时候分享过ChatGPT使用，现在还能用么？

**Comment by jonssonyan** [comment]
> 解决了，对了我记得你以前直播的时候分享过ChatGPT使用，现在还能用么？

https://chat-shared3.zhile.io/shared.html
目前还是可以的，共享账号，挑数字大的点，缺点是限流，不过正常用没问题。
