### ISSUE TITLE
搭建SS使用chacha20新协议无法使用

### ISSUE THREAD

**Issue by thepigeonstar** [trojanpanel/install-script#316]
chacha20
xchacha20
使用这两个协议就无法正常使用
其他正常

**Comment by jonssonyan** [comment]
之前我试过是可以用的，总感觉Xray的SS协议哪里有点问题

**Comment by jonssonyan** [comment]
想整哪块UI

> > 之前我试过是可以用的，总感觉Xray的SS协议哪里有点问题
> 
> 下个月打算干啥，要不整整前端UI

**Comment by thepigeonstar** [comment]
大佬们以后会修复吗  实现完整的ss功能

**Comment by thepigeonstar** [comment]
> 之前我试过是可以用的，总感觉Xray的SS协议哪里有点问题

大佬以后会修复吗 实现完整的ss功能

**Comment by jonssonyan** [comment]
> > 之前我试过是可以用的，总感觉Xray的SS协议哪里有点问题
> 
> 大佬以后会修复吗 实现完整的ss功能

协议找原作者实现，我只做面板。

**Comment by jonssonyan** [comment]
> > 想整哪块UI
> > > > 之前我试过是可以用的，总感觉Xray的SS协议哪里有点问题
> > > 
> > > 
> > > 下个月打算干啥，要不整整前端UI
> 
> 登录界面，希望能更二次元

太花里胡哨了。还是中规中矩点吧
