### ISSUE TITLE
作者好。订阅的时候下载配置很慢请问又解决办法吗。

### ISSUE THREAD

**Issue by luobingwei** [trojanpanel/install-script#319]
作者好。订阅的时候下载配置很慢请问又解决办法吗。

**Comment by jonssonyan** [comment]
改Clash模板，Clash模板里面有一些url被墙了

**Comment by luobingwei** [comment]
请问有什么模板能提供吗？我github里搜到的模板换上去也不行。

**Comment by jonssonyan** [comment]
模板参考的是https://github.com/Loyalsoldier/clash-rules，问我的人都是自己把Clash模板中，被墙的链接替换成自己的oos地址或者自己的urL。
