### ISSUE TITLE
How to update 1.2.0 to 1.3.0 ?

### ISSUE THREAD

**Issue by SKRapToR20** [trojanpanel/install-script#32]
hi there, there is not an option for updating from 1.2 to 1.3, reinstalling trojan panel and trojan panel core also doesn't make an changes, still to naiveproxy option, please help .

**Comment by SKRapToR20** [comment]
how can i backup and restore the data ? can it be done ?

**Comment by raminrez** [comment]
> 

Will we lose data or have an error if we uninstall the panel and core module and install the new one?
