### ISSUE TITLE
希望hysteria2协议的端口跳跃功能

### ISSUE THREAD

**Issue by EventHorizonV** [trojanpanel/install-script#324]
希望通过面板添加hysteria2节点的时候能够添加端口跳跃而不是只支持配置一个端口

**Comment by jonssonyan** [comment]
端口跳跃不是客户端配置的么？服务端不需要配置
https://hysteria.network/zh/docs/advanced/Port-Hopping/#_3

**Comment by EventHorizonV** [comment]
> 端口跳跃不是客户端配置的么？服务端不需要配置
> https://hysteria.network/zh/docs/advanced/Port-Hopping/#_3

原来如此 感谢🙏

**Comment by gyf9835** [comment]
请问可否在生成的Clash.Mate订阅链接中直接加上端口跳跃的配置？这样移动端配置会方便很多。只要在hysteria2节点配置中加一个`ports`配置项就可以了
