### ISSUE TITLE
作者您好，用的旧版，现在想升级，需要怎么做？

### ISSUE THREAD

**Issue by tikkacn** [trojanpanel/install-script#325]
应该还是去年的版本了，版本号都看不到的那种，无法导出用户记录也无法直接更新
现在想重装新版本，但如何保留原来的用户信息和节点信息

**Comment by jonssonyan** [comment]
旧版本不支持自动化升级了，备份一下数据库，重装吧。安装最新版或者[旧版](https://github.com/trojanpanel/install-script/blob/main/README_ARCHIVE_ZH.md)

**Comment by tikkacn** [comment]
好的，问题貌似解决了，谢谢
