### ISSUE TITLE
sysadmin用户名修改并disabled后无法登录

### ISSUE THREAD

**Issue by kampoer** [trojanpanel/install-script#327]
如题，默认的sysadmin帐号修改成别的，昨天关闭账户的时候把修改后的sysadmin也给disabled了，现在面板登陆不了。
从脚本进去reset username和password，登陆sysadmin也提示accound has been disabled
之前改过的sysadmin的管理员也登陆不了，如何解决？

**Comment by jonssonyan** [comment]
脚本更新了，支持重设系统管理员账户状态

**Comment by jonssonyan** [comment]
系统今天更新了，超级管理员角色的用户禁止被禁用
