### ISSUE TITLE
希望加上一个代理转发的功能

### ISSUE THREAD

**Issue by akaagiao1** [trojanpanel/install-script#329]
xray和hy2都支持代理转发，jonsson能否加上代理转发啊以满足观看流媒体和解锁open ai等功能，简单的socks就行

**Comment by jonssonyan** [comment]
今天发的最新版，支持Socks5了，试试，有问题及时反馈

**Comment by akaagiao1** [comment]
谢谢

jonssonyan ***@***.***> 于2023年12月15日周五 22:16写道：
