### ISSUE TITLE
甲骨文实例ubuntu20.4，一键脚本安装后不能打开面板

### ISSUE THREAD

**Issue by Vinparadise** [trojanpanel/install-script#332]
如题，一切顺利安装后，不能打开面板，通过update frontend，发现如下错误

Error response from daemon: Container d29797e406e246297bc4e8ded3fb59ee1e19520441b8f22ac63c54dcab0bd058 is restarting, wait until the container is running
---> The current version does not support online updates

请问如何解决，谢谢

**Comment by jonssonyan** [comment]
脚本里面有查日志的选项，看容器为什么一直在重启的原因是什么

**Comment by Vinparadise** [comment]
> 脚本里面有查日志的选项，看容器为什么一直在重启的原因是什么

好的，我看看再来请教。感谢

**Comment by Vinparadise** [comment]
> 脚本里面有查日志的选项，看容器为什么一直在重启的原因是什么

 The certificate application is abnormal, please try 1. Change the sub-domain name to re-build 2. Restart the server to re-apply for the certificate 3. Re-build and select the custom certificate option
Caddy2 error log is as follows:

---> The Trojan Panel Frontend is running abnormally and the running log is as follows:
2023/12/16 09:37:37 [warn] 1#1: the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/conf.d/default.conf:6
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/conf.d/default.conf:6
感觉跟证书有关，这个应该怎么搞呢，我按照上面的方法重新安装了，也重启了服务器了，还是不行

**Comment by jonssonyan** [comment]
你用的啥域名啊，还有安装时候需要临时监听80端口（因为系统默认申请和续签证书的方式是caddy2），另外不能用一级域名。你看有没有被我说到的。你这个报错我也没遇到过。

**Comment by Vinparadise** [comment]
折腾了一天，把iptable v4删掉，自己手动申请的证书，安装的过程中指定证书的绝对路径，然后就能顺利安装了，也不知道哪里是决定性因素了。回头还得研究一下怎么自动续签呢。我是申请的免费证书，三个月有效。

**Comment by jonssonyan** [comment]
系统默认的证书续签是借助Caddy2实现，只要域名不到期证书就一直往后续签（3个月一次），安装步骤虽然多了一个，但是一劳永逸。
