### ISSUE TITLE
Single User

### ISSUE THREAD

**Issue by ea1234567** [trojanpanel/install-script#35]
Can you make it so that only one person can connect to each generated code? Using the MAC address

**Comment by jonssonyan** [comment]
> Can you make it so that only one person can connect to each generated code? Using the MAC address

Turn off the registration option in the system settings, and then use the sysadmin account to connect to the server, so that only the sysadmin account can be used.

**Comment by ea1234567** [comment]
> > Can you make it so that only one person can connect to each generated code? Using the MAC address
> 
> Turn off the registration option in the system settings, and then use the sysadmin account to connect to the server, so that only the sysadmin account can be used.

for example: i generated one vmess code and i want share that code with my friend
i dont want my friend share that code to someone else . one simultaneous connection (with mac address)

**Comment by jonssonyan** [comment]
> 

Do you mean limit the number of connected devices? Trojan Panel can’t implement it. This is a feature that proxy software needs to add. Trojan-Go supports it but it has a bug (the number of connected devices is set but it doesn’t work). Other proxy software, such as: Xray/Hysteria/NaiveProxy does not support this feature .
