### ISSUE TITLE
想创建在子服务器上的节点，被创建在主服务器上

### ISSUE THREAD

**Issue by 826541814** [trojanpanel/install-script#355]
我的情况说明：
我有A，B两台服务器，A作为主服务器，B只安装了Trojan Panel Core作为子服务器。

服务器列表中的两台服务器都是正常状态， IP .136 是我想新增节点的服务器，如图
<img width="1156" alt="image" src="https://github.com/trojanpanel/install-script/assets/37057859/1ef188e0-4622-403a-a5b1-33e1af057f05">

接下来我添加了节点到 .136 这台服务器中，服务器显示当前节点正常
<img width="1511" alt="image" src="https://github.com/trojanpanel/install-script/assets/37057859/b1f5973e-9597-4bb7-88c6-2b841fd1f437">

更新订阅发现新增的节点无法使用， 查看服务器上进程结果，发现端口8088的节点没有被添加到 .136的服务器， 而是添加到了主服务器中。 
<img width="1165" alt="image" src="https://github.com/trojanpanel/install-script/assets/37057859/83a0f9a1-dd24-4b04-aeda-41b2a750557c">
<img width="836" alt="image" src="https://github.com/trojanpanel/install-script/assets/37057859/11dca864-7643-4a04-822e-e062a715ea47">

我尝试了重新添加子服务器、重新添加节点，都没有能解决问题

**Comment by jonssonyan** [comment]
看了你的复现步骤，操作没什么问题。我还是第一次遇到这样的情况，试试别的类型的节点会不会也是这样，或者在服务器列表把主服务器删掉，添加子服务器的节点在试试。还有我看你用的是旧版的脚本的吧，试试新版的v2.3.2会不会有这个问题。

**Comment by 826541814** [comment]
感谢支持，但还是没有解决我的问题

我按照建议，使用最新的安装脚本更新了两台服务器的Core组件，目前能获取到的最新版好像是 v2.3.1
<img width="1460" alt="image" src="https://github.com/trojanpanel/install-script/assets/37057859/a3334c98-b309-4fa1-a77f-e11975eca6a4">

为了做区分，主服务器端口8100，次节点端口8200， 我在两台服务器上各重新创建了一个节点，主服务器上的还是正常，次服务器上的还是无法使用。
<img width="1505" alt="image" src="https://github.com/trojanpanel/install-script/assets/37057859/484bede6-1f85-42e4-a9e2-96919a66779d">

<img width="230" alt="image" src="https://github.com/trojanpanel/install-script/assets/37057859/dfebad2d-1652-4f3c-a6ee-43c3b835960a">

并且无法访问的服务器上，我并没有找到 8443的监听进程, 甚至我可以用nc命令可以在8443端口上启动一个监听。
不同于上次的是，这次 8443 的节点也没有被创建在主服务器中。所以我很好奇，检测节点是否正常的逻辑是什么
<img width="636" alt="image" src="https://github.com/trojanpanel/install-script/assets/37057859/d3705028-52cf-4f9e-8251-30ba19a57b12">

如图，正常的节点可以被telnet， 异常的那个不行
<img width="846" alt="image" src="https://github.com/trojanpanel/install-script/assets/37057859/597f397d-0054-4236-9399-dd9b59c1cd21">

另外我查看了主节点上的后台日志，在我删除服务器，到重新添加节点时，都没有报错
<img width="1201" alt="image" src="https://github.com/trojanpanel/install-script/assets/37057859/66ff741f-327e-4c29-a4ba-2d99078ce8f2">

**Comment by 826541814** [comment]
后续： 完全删除两个节点服务器，并移除core服务相关容器。 关闭所有防火墙、停止可能冲突的服务后，按上面操作，工作正常。
