### ISSUE TITLE
导出trojan链接（无论直接导出还是订阅）缺少字段

### ISSUE THREAD

**Issue by Zhangxxl** [trojanpanel/install-script#358]
导出的实际链接：trojan-go://_xxxxxxxxxxx-xxxxxx@xxx.xxx.xx:443?sni=xxx.xxx.xx#trojan-go
正确的链接：trojan-go://_xxxxxxxxxxx-xxxxxx@xxx.xxx.xx:443?sni=xxx.xxx.xx&security=tls&alpn=h2,http/1.1&type=tcp#trojan-go
没有security=tls&alpn=h2,http/1.1&type=tcp 这三个参数

**Comment by jonssonyan** [comment]
分享链接这块正在完善，这个问题后面更新上的

**Comment by jonssonyan** [comment]
trojan-go已经不支持了。用xray的trojan协议会有这些字段

**Comment by Zhangxxl** [comment]
> trojan-go已经不支持了。用xray的trojan协议会有这些字段

好的, 换了xray的trojan确实有这些字段了
