### ISSUE TITLE
Backup created user

### ISSUE THREAD

**Issue by ea1234567** [trojanpanel/install-script#36]
How can we backup created users? (Transfer users to other server)

**Comment by jonssonyan** [comment]
> How can we backup created users? (Transfer users to other server)

There is a table in the database, the name of the table is "accout", just copy the data inside to the new database.

**Comment by totem2** [comment]
> Contributor
> ### ** [jonssonyan](/jonssonyan) ** commented [Dec 5, 2022](#issuecomment-1337562406) •

where is the accoount folder?i can't find it

**Comment by gundagai** [comment]
> > Contributor
> > ### ** [jonssonyan](/jonssonyan) ** commented [Dec 5, 2022](#issuecomment-1337562406) •
> 
> where is the accoount folder?i can't find it

It's a table in the database, not a folder in your OS.

**Comment by davodasgharzadeh** [comment]
> > How can we backup created users? (Transfer users to other server)
> 
> #34 There is a table in the database, the name of the table is "accout", just copy the data inside to the new database.

Thank you for your answer. How can I connect to this database?

**Comment by ea1234567** [comment]
> > > How can we backup created users? (Transfer users to other server)
> > 
> > 
> > #34 There is a table in the database, the name of the table is "accout", just copy the data inside to the new database.
> 
> Thank you for your answer. How can I connect to this database?

I have this question too

**Comment by wtst1976** [comment]
> > How can we backup created users? (Transfer users to other server)
> 
> #34 There is a table in the database, the name of the table is "accout", just copy the data inside to the new database.

Hi 
I Used IntelliJ IDEA Community Edition 2022.3.1
But This SoftWare Minimal of ram 4GB need
My Vps have 1GB Of Ram
Which app work with 1GB  of Ram ?
Thanks

**Comment by Technomobile** [comment]
> > How can we backup created users? (Transfer users to other server)
> 
> #34 There is a table in the database, the name of the table is "accout", just copy the data inside to the new database.

cannot find this database file or folder
please help me
