### ISSUE TITLE
请问xray的uuid可以自己设置吗? 或者如何修改呢?

### ISSUE THREAD

**Issue by gundagai** [trojanpanel/install-script#39]
想把旧的uuid导入过来...这样可以不去动客户端的设置了...

**Comment by jonssonyan** [comment]
> 想把旧的uuid导入过来...这样可以不去动客户端的设置了...

用[DataGrip](https://www.jetbrains.com/datagrip/)或者[Navicat](https://www.navicat.com.cn/)之类的连接数据库的工具，将trojan_panel_db里的account表里面的数据复制到新库就可以把用户迁移过来了。

**Comment by gundagai** [comment]
懂了, 那就是不能直接修改了. 谢谢答疑!
