### ISSUE TITLE
搭配好，在QV2RAY连接节点后无法外网

### ISSUE THREAD

**Issue by foxsinyo** [trojanpanel/install-script#40]
日志：
V2Ray 4.31.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 windows/amd64)
A unified platform for anti-censorship.
[Naive] [1206/223629.678:INFO:naive_proxy_bin.cc(419)] Proxying via https://jump.rainko.me:1129
[Naive] [1206/223629.680:INFO:naive_proxy_bin.cc(564)] Listening on 127.0.0.1:15000
2022/12/06 22:36:30 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
v2ctl> Read config:  C:/Users/Administrator/AppData/Local/qv2ray/generated/config.gen.json
2022/12/06 22:36:30 [Warning] v2ray.com/core: V2Ray 4.31.0 started
2022/12/06 22:36:30 127.0.0.1:58427 accepted tcp:127.0.0.1:0 [QV2RAY_API]
2022/12/06 22:36:40 127.0.0.1:58446 accepted //mail.google.com:443 [PROXY]
[Naive] [1206/223640.583:INFO:naive_connection.cc(273)] Connection 1 to mail.google.com:443
2022/12/06 22:36:40 127.0.0.1:58449 accepted //mail.google.com:443 [PROXY]
[Naive] [1206/223640.645:INFO:naive_connection.cc(273)] Connection 2 to mail.google.com:443
2022/12/06 22:36:41 127.0.0.1:58453 accepted //beacons.gcp.gvt2.com:443 [PROXY]
[Naive] [1206/223641.040:INFO:naive_connection.cc(273)] Connection 3 to beacons.gcp.gvt2.com:443
[Naive] [1206/223641.063:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223641.107:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223641.304:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223641.523:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223641.562:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223641.562:INFO:naive_proxy.cc(192)] Connection 2 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [1206/223641.594:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223641.595:INFO:naive_proxy.cc(192)] Connection 1 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [1206/223641.816:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223642.059:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223642.059:INFO:naive_proxy.cc(192)] Connection 3 closed: ERR_PROXY_CONNECTION_FAILED
2022/12/06 22:36:42 127.0.0.1:58463 accepted //mail.google.com:443 [PROXY]
[Naive] [1206/223642.568:INFO:naive_connection.cc(273)] Connection 4 to mail.google.com:443
2022/12/06 22:36:42 127.0.0.1:58466 accepted //mail.google.com:443 [PROXY]
[Naive] [1206/223642.596:INFO:naive_connection.cc(273)] Connection 5 to mail.google.com:443
2022/12/06 22:36:42 127.0.0.1:58469 accepted //suggestion.baidu.com:443 [PROXY]
[Naive] [1206/223642.656:INFO:naive_connection.cc(273)] Connection 6 to suggestion.baidu.com:443
2022/12/06 22:36:43 127.0.0.1:58476 accepted //beacons.gcp.gvt2.com:443 [PROXY]
[Naive] [1206/223643.071:INFO:naive_connection.cc(273)] Connection 7 to beacons.gcp.gvt2.com:443
[Naive] [1206/223643.076:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223643.123:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223643.184:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223643.604:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223643.604:INFO:naive_proxy.cc(192)] Connection 5 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [1206/223643.607:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223643.651:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223643.651:INFO:naive_proxy.cc(192)] Connection 4 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [1206/223643.691:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223643.692:INFO:naive_proxy.cc(192)] Connection 6 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [1206/223643.820:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
2022/12/06 22:36:43 127.0.0.1:58485 accepted //youtube.com:443 [PROXY]
[Naive] [1206/223643.946:INFO:naive_connection.cc(273)] Connection 8 to youtube.com:443
2022/12/06 22:36:43 127.0.0.1:58488 accepted //fonts.googleapis.com:443 [PROXY]
2022/12/06 22:36:43 127.0.0.1:58486 accepted //www.youtube.com:443 [PROXY]
[Naive] [1206/223643.947:INFO:naive_connection.cc(273)] Connection 9 to fonts.googleapis.com:443
[Naive] [1206/223643.948:INFO:naive_connection.cc(273)] Connection 10 to www.youtube.com:443
2022/12/06 22:36:43 127.0.0.1:58494 accepted //fonts.gstatic.com:443 [PROXY]
[Naive] [1206/223643.953:INFO:naive_connection.cc(273)] Connection 11 to fonts.gstatic.com:443
[Naive] [1206/223644.062:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223644.062:INFO:naive_proxy.cc(192)] Connection 7 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [1206/223644.286:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223644.421:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223644.422:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223644.422:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223644.424:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
2022/12/06 22:36:44 127.0.0.1:58502 accepted //mail.google.com:443 [PROXY]
[Naive] [1206/223644.660:INFO:naive_connection.cc(273)] Connection 12 to mail.google.com:443
2022/12/06 22:36:44 127.0.0.1:58505 accepted //suggestion.baidu.com:443 [PROXY]
[Naive] [1206/223644.694:INFO:naive_connection.cc(273)] Connection 13 to suggestion.baidu.com:443
[Naive] [1206/223644.796:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223644.959:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223644.959:INFO:naive_proxy.cc(192)] Connection 8 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [1206/223644.960:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223644.960:INFO:naive_proxy.cc(192)] Connection 11 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [1206/223644.960:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223644.960:INFO:naive_proxy.cc(192)] Connection 10 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [1206/223644.961:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223644.961:INFO:naive_proxy.cc(192)] Connection 9 closed: ERR_PROXY_CONNECTION_FAILED
2022/12/06 22:36:44 127.0.0.1:58510 accepted //beacons.gcp.gvt2.com:443 [PROXY]
[Naive] [1206/223644.971:INFO:naive_connection.cc(273)] Connection 14 to beacons.gcp.gvt2.com:443
[Naive] [1206/223645.173:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223645.203:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223645.295:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223645.296:INFO:naive_proxy.cc(192)] Connection 13 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [1206/223645.403:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223645.442:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223645.606:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223645.606:INFO:naive_proxy.cc(192)] Connection 12 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [1206/223645.634:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223645.821:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223645.864:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223645.864:INFO:naive_proxy.cc(192)] Connection 14 closed: ERR_PROXY_CONNECTION_FAILED
2022/12/06 22:36:45 127.0.0.1:58517 accepted //www.youtube.com:443 [PROXY]
2022/12/06 22:36:45 127.0.0.1:58519 accepted //youtube.com:443 [PROXY]
2022/12/06 22:36:45 127.0.0.1:58518 accepted //fonts.googleapis.com:443 [PROXY]
2022/12/06 22:36:45 127.0.0.1:58520 accepted //fonts.gstatic.com:443 [PROXY]
[Naive] [1206/223645.974:INFO:naive_connection.cc(273)] Connection 15 to www.youtube.com:443
[Naive] [1206/223645.974:INFO:naive_connection.cc(273)] Connection 16 to youtube.com:443
[Naive] [1206/223645.974:INFO:naive_connection.cc(273)] Connection 17 to fonts.googleapis.com:443
[Naive] [1206/223645.975:INFO:naive_connection.cc(273)] Connection 18 to fonts.gstatic.com:443
2022/12/06 22:36:46 127.0.0.1:58529 accepted //clients2.google.com:443 [PROXY]
[Naive] [1206/223646.066:INFO:naive_connection.cc(273)] Connection 19 to clients2.google.com:443
[Naive] [1206/223646.461:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223646.461:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223646.463:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223646.464:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223646.564:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
2022/12/06 22:36:46 127.0.0.1:58538 accepted //mail.google.com:443 [PROXY]
[Naive] [1206/223646.607:INFO:naive_connection.cc(273)] Connection 20 to mail.google.com:443
2022/12/06 22:36:46 127.0.0.1:58541 accepted //suggestion.baidu.com:443 [PROXY]
[Naive] [1206/223646.704:INFO:naive_connection.cc(273)] Connection 21 to suggestion.baidu.com:443
[Naive] [1206/223646.789:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
2022/12/06 22:36:46 127.0.0.1:58545 accepted //beacons.gcp.gvt2.com:443 [PROXY]
[Naive] [1206/223646.869:INFO:naive_connection.cc(273)] Connection 22 to beacons.gcp.gvt2.com:443
[Naive] [1206/223646.905:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223646.905:INFO:naive_proxy.cc(192)] Connection 16 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [1206/223646.907:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223646.907:INFO:naive_proxy.cc(192)] Connection 18 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [1206/223646.908:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223646.908:INFO:naive_proxy.cc(192)] Connection 15 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [1206/223646.911:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223646.911:INFO:naive_proxy.cc(192)] Connection 17 closed: ERR_PROXY_CONNECTION_FAILED
2022/12/06 22:36:47 127.0.0.1:58548 accepted //optimizationguide-pa.googleapis.com:443 [PROXY]
[Naive] [1206/223647.018:INFO:naive_connection.cc(273)] Connection 23 to optimizationguide-pa.googleapis.com:443
[Naive] [1206/223647.025:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223647.025:INFO:naive_proxy.cc(192)] Connection 19 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [1206/223647.065:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223647.192:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223647.292:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223647.394:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223647.534:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223647.596:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223647.597:INFO:naive_proxy.cc(192)] Connection 20 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [1206/223647.643:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223647.718:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223647.718:INFO:naive_proxy.cc(192)] Connection 21 closed: ERR_PROXY_CONNECTION_FAILED
[Naive] [1206/223647.788:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107
[Naive] [1206/223647.897:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -107

**Comment by jonssonyan** [comment]
用最新版试试吧。

**Comment by jonssonyan** [comment]
换个客户端试试，比如nekoray
