### ISSUE TITLE
手动安装缺少 docker-compose 配置

### ISSUE THREAD

**Issue by kilvn** [trojanpanel/install-script#48]
自动安装不能可选是否要安装mysql和Redis，实际上已经安装了，确实可选项。

手动安装只有 docker run 这是很不方便的，docker-compose 配置一丢，启动很方便的

**Comment by neweva** [comment]
你可以嘗試用這個轉換https://www.composerize.com/為compose

**Comment by kilvn** [comment]
> 

好的，拴Q
