### ISSUE TITLE
Clash订阅地址 使用配置文件时报错

### ISSUE THREAD

**Issue by Qlmuby** [trojanpanel/install-script#50]
如图红框那一行的双逗号之间貌似缺点东西，导致使用配置的时候一直报错。
![Clash_Verge_KzaXhgAC4J](https://user-images.githubusercontent.com/55885455/206612221-dd724c2e-284d-4be7-824e-b8f6700fbce5.png)

**Comment by Mrered** [comment]
建议作者修改一下，我手动删除这一行就好了，另外我的订阅规则有12000多字符，面板Clash规则这里限制字符数10000，可否提高字符数限制？ @jonssonyan  感谢作者！

**Comment by jonssonyan** [comment]
下个版本放开到10W个字符了。等等下个版本发布吧

**Comment by Mrered** [comment]
> 下个版本放开到10W个字符了。等等下个版本发布吧

Ohhhhhh！好耶，如果官方能做一个下拉菜单，就像订阅地址转换工具里那样，包含一些常见rules（比如lhie1），那就更好了！

**Comment by jonssonyan** [comment]
已经支持了
