### ISSUE TITLE
安卓用calsh无法订阅地址

### ISSUE THREAD

**Issue by kissimok** [trojanpanel/install-script#51]
.
安卓客户端订阅提示错误..
错误

rules[OJ [RULE-SET,applications,DIRECT error: unsupported rule type RULE-SET

**Comment by jonssonyan** [comment]
订阅功能在最新版完善了，但是默认的Clash模板里面有部分url被墙，需要自己改一下。
参考的这个项目的Clash模板：https://github.com/Loyalsoldier/clash-rules
