### ISSUE TITLE
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by certifiedtruecopy** [trojanpanel/install-script#54]
安装时间随此消息一起出现

---> 安装Trojan Panel
请输入数据库的IP地址(默认:本机数据库):
请输入数据库的端口(默认:9507):
请输入数据库的用户名(默认:root):
请输入数据库的密码(必填): fr*pr&mU6r9bltu
**ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)**
请输入Redis的IP地址(默认:本机Redis)

**Comment by sarakh55** [comment]
Hi
What's the problem dear friend?

**Comment by certifiedtruecopy** [comment]
Hello dear friend 

The following error is encountered during installation
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

And when I enter the panel, I get a 502 error message

**Comment by sarakh55** [comment]
Hello my dear friend
What should I do?

**Comment by certifiedtruecopy** [comment]
I had this problem only in Ubuntu 22.04. When I tried it on Centos 7, it was solved

**Comment by jonssonyan** [comment]
系统的问题，换个系统或者DD系统。有点系统安装Docker之后运行MariaDB容器，会出现拒绝root用户访问数据库，但其实是在使用install-script安装TP时候设置了root密码。
