### ISSUE TITLE
Request failed with status code 502

### ISSUE THREAD

**Issue by MinghoiMok** [trojanpanel/install-script#57]
登入Trojan Panel 面板的時候彈出 Request failed with status code 502
鍵入 用戶名和密碼后再次彈出 Request failed with status code 502

**Comment by jonssonyan** [comment]
查下日志

**Comment by MinghoiMok** [comment]
{"level":"error","msg":"数据库连接异常 err: Error 1130: Host '209.141.**.***' is not allowed to connect to this MariaDB server","time":"2022-12-12 00:47:47"}
{"level":"error","msg":"数据库连接异常 err: Error 1130: Host '209.141.**.***' is not allowed to connect to this MariaDB server","time":"2022-12-12 00:47:47"}
{"level":"error","msg":"数据库连接异常 err: Error 1130: Host '209.141.**.***' is not allowed to connect to this MariaDB server","time":"2022-12-12 00:47:47"}
{"level":"error","msg":"数据库连接异常 err: Error 1130: Host '209.141.**.***' is not allowed to connect to this MariaDB server","time":"2022-12-12 00:47:48"}
{"level":"error","msg":"数据库连接异常 err: Error 1130: Host '209.141.**.***' is not allowed to connect to this MariaDB server","time":"2022-12-12 00:47:49"}
{"level":"error","msg":"数据库连接异常 err: Error 1130: Host '209.141.**.***' is not allowed to connect to this MariaDB server","time":"2022-12-12 00:47:51"}
{"level":"error","msg":"数据库连接异常 err: Error 1130: Host '209.141.**.***' is not allowed to connect to this MariaDB server","time":"2022-12-12 00:47:54"}
{"level":"error","msg":"数据库连接异常 err: Error 1130: Host '209.141.**.***' is not allowed to connect to this MariaDB server","time":"2022-12-12 00:48:01"}
{"level":"error","msg":"数据库连接异常 err: Error 1130: Host '209.141.**.***' is not allowed to connect to this MariaDB server","time":"2022-12-12 00:48:14"}
{"level":"error","msg":"数据库连接异常 err: Error 1130: Host '209.141.**.***' is not allowed to connect to this MariaDB server","time":"2022-12-12 00:48:40"}
{"level":"error","msg":"数据库连接异常 err: Error 1130: Host '209.141.**.***' is not allowed to connect to this MariaDB server","time":"2022-12-12 00:49:31"}
{"level":"error","msg":"数据库连接异常 err: Error 1130: Host '209.141.**.***' is not allowed to connect to this MariaDB server","time":"2022-12-12 00:50:31"}

**Comment by Mohammadjsh** [comment]
my problem as well

**Comment by saostad** [comment]
This is ridiculous, but it only worked for me using  123456 as MariaDB and Redis password. 
This is not a recommendation and if you are using this password, make sure to block the MariaDB and Redis ports from your server firewall.

**Comment by jonssonyan** [comment]
后端和数据库之间连通性有问题，看看是不是数据库密码设置太简单了。会被撞库，导致被人删库。

**Comment by Mohammadjsh** [comment]
i think its cause linux i dont have any problem with centos 7 try this
