### ISSUE TITLE
error during installing script

### ISSUE THREAD

**Issue by shahinfard93** [trojanpanel/install-script#59]
你的域名没有解析到本机IP,请稍后再试
---> Caddy安装失败

- i get this error after selecting auto renewal. it translates to "Your domain name is not resolving to the local IP, please try again later"
- but I'm sure the domain point to the server IP. Don't know waht the problem is....

**Comment by hossein-a-z** [comment]
I have the same problem here

**Comment by navidtrc** [comment]
Same problem!

**Comment by alemsas** [comment]
same problem!
is there any solution?

**Comment by alemsas** [comment]
Any solution?!

**Comment by jonssonyan** [comment]
It has been repaired, and the logic of verifying IP has been removed.
