### ISSUE TITLE
无法访问Trojan panel

### ISSUE THREAD

**Issue by RookieTerry** [trojanpanel/install-script#6]
如图，Trojan-go数据库版已经安装成功了，亚马逊云安全组均已放行，浏览器无法访问域名:8888，不知道为什么
![屏幕截图 2022-05-01 123606](https://user-images.githubusercontent.com/77920425/166132401-24088a53-9782-457d-a9a1-6491a68d5d2f.jpg)

**Comment by jonssonyan** [comment]
首先你使用`docker ps`命令查看一下哪些服务启动失败了，可以对症下药。

### 可能的原因

之前遇到这种问题基本上都是证书申请失败了，可以到`/tpdata/caddy/acme/你的域名/`这个目录下面查看一下是否有`.key` `.crt`文件，如果没有这两个文件，则说明证书申请失败。

### 解决办法

1. 可以重启服务器这会重新尝试申请证书。
2. 自定义证书，在搭建时候会有一个步骤是`请选择设置证书的方式?(1/自动申请和续签证书 2/手动设置证书路径 默认:1/自动申请和续签证书)`默认选择的是1，这里你可以选择2，然后将自定义的证书路径输入到命令行。需要提前准备好自己申请的证书，并上传到服务器。

### 补充

推荐两个申请免费证书的工具和网站
1. https://github.com/acmesh-official/acme.sh （推荐）
2. https://freessl.cn/ （需要注册并绑定手机）

**Comment by jonssonyan** [comment]
脚本已经更新，可以尝试再次搭建看会不会有问题。
