### ISSUE TITLE
Trojan Panel with Cloudflare CDN?

### ISSUE THREAD

**Issue by leomoon** [trojanpanel/install-script#60]
This panel is great.

Is it possible to set this up with Cloudflare CDN to reduce the  risk of IP blocking?

I tried enabling it on Cloudflare but the panel is not loading anymore:
![image](https://user-images.githubusercontent.com/3268946/206933355-faa60ae2-ac48-4de5-ae18-c8d83b7fadec.png)

**Comment by 3ehzaad** [comment]
To get into the panel you should use your real IP with the same port, instead of your domain record  ... 
It will be HTTP though and I am guessing some functions will not work properly
