### ISSUE TITLE
Traffic limit and Expiration date for Nodes

### ISSUE THREAD

**Issue by zekerya** [trojanpanel/install-script#63]
It would be perfect if you could add Traffic limit and Expiration date for Nodes too.
Thanks

**Comment by zekerya** [comment]
Still waiting....... 🥇

**Comment by zekerya** [comment]
Day 22 of waiting for this option.......

**Comment by jonssonyan** [comment]
Trojan-panel-core is based on xray-core, trojan-go, hysteria, and naiveproxy. Currently, hysteria and naiveproxy do not support flow control, so trojan-panel-core cannot directly support it. You can submit an issue under the projects of hysteria and naiveproxy
