### ISSUE TITLE
502 Error - Mariadb 

### ISSUE THREAD

**Issue by Theod0r** [trojanpanel/install-script#65]
When I try to access the panel through the web, I get " Request failed with status code 502 " 

I checked the log and got this :
` "{"level":"error","msg":"数据库连接异常 err: Error 1130: Host '127.0.0.1' is not allowed to connect to this MariaDB server","time":"2022-12-14 18:28:21"}`

Any help please?

**Comment by Mohammadjsh** [comment]
yeah thats my problem as well

**Comment by essoojay** [comment]
Same with me, i tried on ubuntu 20.04, then centos 7 same error: Request failed with status code 502

anybody help?

**Comment by jonssonyan** [comment]
Install a clean version of the operating system
