### ISSUE TITLE
timeout of 5000ms exceeded

### ISSUE THREAD

**Issue by Farzad292** [trojanpanel/install-script#66]
I just receive timeout of 5000ms exceeded error when click any bottom of panel or want to login
my internet ping is about 7000ms!

**Comment by koohsaran** [comment]
I have this problem too

**Comment by Sinoxsep** [comment]
someone help us to solve this error :(

**Comment by erfannjz** [comment]
Im too

**Comment by jonssonyan** [comment]
try to reinstall
