### ISSUE TITLE
can't create any node 

### ISSUE THREAD

**Issue by halfaaa** [trojanpanel/install-script#68]
i want to create nodes in my panel but i get this error : 远程服务连接失败,请检查远程服务配置
also sometimes i get this error:  "timeout of 5000ms exceeded"
i have to say sometimes accidentally a node created but "time out" is showing in the status column.
i didn't get any error in the installation process, and everything installed successfully.

**Comment by Plus1979** [comment]
I have exactly the same problem.

**Comment by koohsaran** [comment]
And i!

**Comment by siyamakkk** [comment]
hi this problam for mi
远程服务连接失败,请检查远程服务配置

**Comment by jonssonyan** [comment]
try latest version v2.1.x
