### ISSUE TITLE
hysteria协议和naiveproxy协议中转问题

### ISSUE THREAD

**Issue by 18690819111** [trojanpanel/install-script#71]
你好大神，我想问一下hysteria协议和naiveproxy协议是不支持中转么？我用gost的tcp加udp、还有iptables中转都不能正常的连通（直连是通的）。其他协议，如xray、vl、vm都能正常的支持。
是我没有配置对？还是协议不支持？

**Comment by jonssonyan** [comment]
这个问题你应该到hysteria、naiveproxy项目下面提issue
https://github.com/apernet/hysteria/issues
https://github.com/klzgrad/naiveproxy/issues
