### ISSUE TITLE
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by NadiaGarcia6** [trojanpanel/install-script#74]
When I trying to install Trojan-Panel via the recommended official script, I get this error, I have check it on CentOS7 and Debian 11
Last version did not have this problem

-------------------------------------

6.2.7: Pulling from library/redis
Digest: sha256:a93c14584715ec5bd9d2648d58c3b27f89416242bee0bc9e5fb2edc1a4cbec1d
Status: Image is up to date for redis:6.2.7
docker.io/library/redis:6.2.7
a9e8a38263ad3c98e805de450342a06cf70e9e86b92d793886ff4959fc2553e0
---> Redis安装完成
---> Redis的数据库密码(请妥善保存): GmailGoogle123
---> 安装Trojan Panel
请输入数据库的IP地址(默认:本机数据库): 
请输入数据库的端口(默认:9507): 
请输入数据库的用户名(默认:root): 
请输入数据库的密码(必填): GmailGoogle123
**ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)**

**Comment by NadiaGarcia6** [comment]
![image](https://user-images.githubusercontent.com/119847856/208233622-5ecbce87-6be1-4cb6-9c56-15c4efeba57b.png)


![image](https://user-images.githubusercontent.com/119847856/208233633-7c5bef49-47d8-4560-9a2e-a1ea76426ff4.png)

**Comment by jonssonyan** [comment]
换个操作系统，例如CentOS7
