### ISSUE TITLE
clean issues

### ISSUE THREAD

**Issue by netsupcloud** [trojanpanel/install-script#78]
hi these issues as my first test are obvious:
1-trojan panel core cpu usage will spike high about 70-80%
2-sysadmin cant get qr code of user unless only login in his panel
3-update option in script in centos 8(didnt check others) will close terminal only and doesnt work
4-vmess ws or tcp are not importable in any client software

**Comment by jonssonyan** [comment]
1. To be verified, is it a Trojan Panel problem?
2. This is how the system is designed. The administrator can only manage users. To obtain the user's QR code, you need to log in to the user's account.
3. The update option is not mature yet, it is just a preparation for automatic upgrade in the future
4. Xray vmess is vmess AEAD, which is different from the normal vmess format. You can refer to the xray sharing link proposal: https://github.com/XTLS/Xray-core/issues/91
