### ISSUE TITLE
初次使用bug汇总

### ISSUE THREAD

**Issue by youjiajia-wc** [trojanpanel/install-script#8]
1.重装未校验过程的准确性：
 1.1 数据库密码输入错误，仍继续安装；
 1.2 Redis密码输入错误，仍继续安装
2.拓展性不够好：
 2.1 证书不支持手动输入路径，对于NAT机器和无公网ipv4的机器毫无支持；
 2.2 卸载重装不校验/选择证书，如果第一次域名输入了特定值，如localhost，将永远不能重新申请证书和安装
3.比较吃资源
 3.1 Redis一般是把数据库的值放在内存以提高访问速度，但多数人的可能配置都不高。说人话就是技术人员的架构可能脱离了使用者的场景。
因本人的测试机没有安装成功，先写这么多吧。如果不合眼，请轻喷。

**Comment by jonssonyan** [comment]
> 1.重装未校验过程的准确性： 1.1 数据库密码输入错误，仍继续安装； 1.2 Redis密码输入错误，仍继续安装 2.拓展性不够好： 2.1 证书不支持手动输入路径，对于NAT机器和无公网ipv4的机器毫无支持； 2.2 卸载重装不校验/选择证书，如果第一次域名输入了特定值，如localhost，将永远不能重新申请证书和安装 3.比较吃资源 3.1 Redis一般是把数据库的值放在内存以提高访问速度，但多数人的可能配置都不高。说人话就是技术人员的架构可能脱离了使用者的场景。 因本人的测试机没有安装成功，先写这么多吧。如果不合眼，请轻喷。

感谢你的反馈

1.1&1.2 数据库和Redis确实没校验不太人性化，加点逻辑判断即可。
2.1 证书可以自定义输入指定路径（可能是你没走到这一步脚本就退出了），在安装Caddy时候有个选项可以选择自动申请或者自己指定本机证书的绝对路径。在校验域名的时候有个逻辑ping不通会退出脚本，加这个逻辑因为考虑到有人没解析到IP就搭建结果必定导致自动申请证书失败。当时没考虑到NAT机器和无公网ipv4的机器，所以把ping逻辑放到自动申请选项的后续逻辑即可。
2.2 加个替换证书选项即可或者卸载Trojan Panel时将Caddy一并卸载即可。
3.1 Redi完全基于内存，没有大量IO操作，本身不占很多内存，往往系统中性瓶颈都是IO操作较多的应用，所以真正的瓶颈是MariaDB，见图2。

最后一个问题，我是一名极客，一般不会反感别人的建议。如果真遇到分歧不过是每个人站的角度不同。

总结，目前一键部署脚本还不够人性化，总的来说问题不大。

以下是性能测试：

在安装教程里已经注明服务器内存需要≥1G，所以测试服务器配置：CentOS7 x86_64 1H1G。如果实在没1G内存的丐版机器，还是用单机版吧，装个面板真不合适。

图1：一共安装7个服务，运行一个星期，实际使用内存不到600M。
![image](https://user-images.githubusercontent.com/46235235/169095325-22252307-84ee-4315-8189-5e9946831e2a.png)

图2：这是所有服务的性能监控，Redis（trojan-panel-redis）的内存占用（MEM USAGE）为8.551MiB低于除了前端应用（trojan-panel-ui）的所有其他应用，对于1G内存的服务器这点消耗可以忽略不记，所以不存在Redis是冗余设计，而且引入缓存可以加快系统响应速度和实现更多业务，利大于弊。
![image](https://user-images.githubusercontent.com/46235235/169095550-b0867921-61fe-43f1-ab89-8e6a01f07a8f.png)

**Comment by youjiajia-wc** [comment]
谢谢你的回答。
我设置hosts的域名为127.0.0.1安装成功了。
本来想修改证书的手动选择，发现你已经回复过了。
所以2.1部分，不是问题。
我只安装 了面板，内存比裸系统多了约300M，应该还是接受范围。
1.重装：
    为菜单3安装失败，比如输入域名，ping失败，再5卸载，然后再3安装

原则上不应该在这里补充的，再给你补充几个：
4.易用性：
4.1 新增用户的用户名不应该限制：因为Trojan只检验密码，用户名输汉字反而有利于我认人，长度的限制也应该取消；
4.2 新增用户的密码不应该限制：因为Trojan未限制，我最短用过3位密码的都ok，没尝试1位，理论上应该也可以。
4.3 新增用户的过期时间不应该定位到当前的时间，因为新增过期用户毫无意义，每次新增都要手动去改，比如5/19新建，放6/19 24过期；
4.4 新增用户的流量不应该设置为0，理由同上。
4.5 节点管理，新增节点时，应该默认端口443
4.6 系统设置，基础设置新用户的默认流量，建议管理员新增的时候默认流量也读取这个值
5. 用户列表，编辑存在bug，原因未知：
新增用户，输入用户名和密码后确定。再编辑该用户，仅修改流量为-1.后端报参数无效
/api/users/updateUserById

**Comment by youjiajia-wc** [comment]
再提出几点异议：
1.我不知道你ping的逻辑是什么，是不是直接ping域名？如果是，有可能存在输入的域名并非是自己的机器，比如我香港有两个服务器，二级主机名分别是hk1和hk2，输错了你也能ping通。
建议ping域名的ip，与curl ifconfig.me比对； 
对于4.1 & 4.2，你的设计我不否认出发点的考虑，但是首先就不能对已有的用户数据进行兼容。那就意味着用你面板的人，那些存量用户都要单独修改。

**Comment by jonssonyan** [comment]
感谢，这个项目因为你的提议越来越好了。
检测IP本来打算自己写的，但是自己写好像判断比较多不太通用一直耽搁着，想不依赖第三方，因为怕它挂了。先用第三方吧，写的快。
初心是做个Trojan的面板，类型的话目前主要支持Trojan-go，刚开始写有想过关联表，但是目前是没有必要不是刚需，主要考虑到连接查询会慢一点，一张表能搞定的没必要搞两张，而且每次更新两张表，会有锁和事务的问题在里面，前期先不搞复杂了，另外现在users表字段数量不多是在可接受的范围内。以后可能支持协议越来越多最后会如你所说做连表操作。
