### ISSUE TITLE
Sysadmin Reset Password

### ISSUE THREAD

**Issue by msh71** [trojanpanel/install-script#81]
hi 
i forgot sysadmin password , how can i do reset it?

**Comment by jonssonyan** [comment]
If you forget the password of the super administrator, there are two solutions:
1. Reinstall the system, the initial password of sysadmin is 123456
2. Change the row corresponding to sysadmin in the account table in the trojan_panel_db database, and change the pass field value to `tFjD2X1F6i9FfWp2GDU5Vbi1conuaChDKIYbw9zMFrqvMoSz` hash field value to `4366294571b8b267d9cf15b56660f0a706595680a952fc27` At this point the sysadmin password will be changed to 123456
