### ISSUE TITLE
High ping and Near Zero Upload speed

### ISSUE THREAD

**Issue by mehradraissi** [trojanpanel/install-script#82]
Hey Guys, 
Since Satuday, the government did something to the Internet and suddenly my Ping jumped from 50 to 600+ sometimes 1200 , The download speed hasn't changed and it's great but the upload speed is 0.01MB ( near zero ) , Any ideas ? 
it hapend before i managed to change the ports to 5 digits (10000+) and it fixed everything, but i have tested the ports (100-30000) nothing seems to be working.

**Comment by jonssonyan** [comment]
This is beyond the range that Trojan Panel can handle, you can try another VPS

**Comment by mehradraissi** [comment]
even if it was working fine before !? 
isn't there something i can check or change vps ?!
