### ISSUE TITLE
Active access log

### ISSUE THREAD

**Issue by morteza-rashidi** [trojanpanel/install-script#83]
Hello,
can anyone tell me, how can I Active access log (same access.log) ?
please help me

**Comment by jonssonyan** [comment]
The Trojan Panel log file location is as follows
/tpdata/trojan-panel/logs/
The location of the Trojan Panel Core log file is as follows
/tpdata/trojan-panel-core/logs/
Caddy log file location is as follows
/tpdata/trojan-panel-core/logs
Run the log view command as follows
docker logs [container name] For example: view trojan-panel operation log docker logs trojan-panel

**Comment by morteza-rashidi** [comment]
These logs only contain error information and do not include connection reports and requests
