### ISSUE TITLE
created node fail in V2rayng

### ISSUE THREAD

**Issue by msh1979** [trojanpanel/install-script#84]
hi guys,
i have created the trojan panel but i could just create vless. the other protocols like vmess trojan go and ... could be create in panel but when i wanted to transfer the configuration to android app (v2rayng or napsternetv) it fails. i tried different method to transfer configuration like QR code or copy URL but non of them working.

as i said the only protocol that works is Vless

**Comment by Obeid1375** [comment]
Use shadow rocket for ios and sagernet for android
