### ISSUE TITLE
Please contact the system administrator

### ISSUE THREAD

**Issue by mbaqry101** [trojanpanel/install-script#87]
System error Please contact the system administrator

When I try to enter my panel, it gives this error

**Comment by mbaqry101** [comment]
Please contact the system administrator

**Comment by outlander65** [comment]
You should use only letters and numbers for your password. uninstall and reinstall, this time every time enter a passwords that is just the combination of letters and numbers and NOT the special characters like #$@

**Comment by mbaqry101** [comment]
But my username and password are the default

**Comment by jonssonyan** [comment]
You are the builder of the system, and you are the system administrator. If this error occurs, it means that the system has not been built successfully.
