### ISSUE TITLE
WhatsApp calls not working

### ISSUE THREAD

**Issue by r0zbeh** [trojanpanel/install-script#90]
hi nearlly most video and audio messenger systems not working when using vless vmess , how can i resolve this issue?

**Comment by r0zbeh** [comment]
Instagram video and voice call work good, when call (video and voice) with whatsapp , the other side ring but when answer , app stuk in connecting and connection close after few second?!? Whats the problem why whatsapp dont work properly?

**Comment by Mo3M** [comment]
For the sake of curiosity, which transport protocol are you using? Is it WS (websocket) by any chance?

**Comment by r0zbeh** [comment]
protocol is Vmess-ws-lts and i dont use cloadflare

**Comment by r0zbeh** [comment]
Same ProlWith Telegram Voice call and Video call !!

**Comment by Mo3M** [comment]
Did you manage to solve the problem?
