### ISSUE TITLE
clash 配置文件失败 Trojan Panel：1.3.2

### ISSUE THREAD

**Issue by qinjinghub2** [trojanpanel/install-script#91]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/54932882/209657093-1629ae23-2916-4d7f-940b-98011c265d00.png">

clash版本：最新

**Comment by qinjinghub2** [comment]
<img width="1080" alt="截屏2022-12-27 19 13 14" src="https://user-images.githubusercontent.com/54932882/209658651-ec0f2df0-4f22-4d1a-8d4e-ee13a61f01ef.png">
proxies is none, please fix

**Comment by qinjinghub2** [comment]
<img width="1080" alt="截屏2022-12-27 19 13 14" src="https://user-images.githubusercontent.com/54932882/209658651-ec0f2df0-4f22-4d1a-8d4e-ee13a61f01ef.png">
proxies is none, please fix

**Comment by jonssonyan** [comment]
try latest version
