### ISSUE TITLE
Server is shown empty when add node

### ISSUE THREAD

**Issue by Artitrader** [trojanpanel/install-script#94]
when for first time i want add node in trojan panel there is a necessary field called server that could not be changed and for me it is empty. it is first time i see it . what is this and what is the solution (it shows nothing at all)

![000000001](https://user-images.githubusercontent.com/97684218/209858171-a03f23fc-e456-4789-a1a3-14f734bd5973.jpg)

**Comment by peyman24x** [comment]
First you need to add your server in the server tab

**Comment by Artitrader** [comment]
thanks . i tried it and solved
