### ISSUE TITLE
error WebSocket

### ISSUE THREAD

**Issue by peyman24x** [trojanpanel/install-script#95]
Does anyone know the reason for this error message on Vless+ws+tls?

app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxx.xx:2083/trojan-panel-websocket-path):  > EOF transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxx.xx:2083/trojan-panel-websocket-path):  > dial tcp: lookup xxx.xx: operation was canceled] > common/retry: all retry attempts failed

**Comment by jonssonyan** [comment]
Vless+ws+tls I tried it and it works, check the configuration of your own server
