### ISSUE TITLE
Update not Working

### ISSUE THREAD

**Issue by aliruss** [trojanpanel/install-script#99]
hi 

i use an old version of trojan panel and now i wana to upgrade it buy it did'nt work

**Comment by jonssonyan** [comment]
> hi
> 
> i use an old version of trojan panel and now i wana to upgrade it buy it did'nt work

https://github.com/trojanpanel/install-script/issues/99#issue-1516827463

> hi
> 
> i use an old version of trojan panel and now i wana to upgrade it buy it did'nt work

Automatic upgrades are only supported after v1.3.1

**Comment by peyman24x** [comment]
hello how can use Automatic upgrade?

**Comment by jonssonyan** [comment]
> hello how can use Automatic upgrade?

There is an automatic update option in the one-click installation script
